import type {
  DashboardRegion,
  DashboardRegionLanguage,
} from "@/lib/dashboard-regions";
import { categoryLabelWithIcon } from "@/lib/category-display";

type CategoryLike = { id: string; label: string };

const CATEGORY_LABELS: Record<string, Partial<Record<DashboardRegionLanguage, string>>> = {
  all: {
    telugu: "అన్నీ",
    hindi: "सभी",
    tamil: "அனைத்தும்",
    kannada: "ಎಲ್ಲವೂ",
    malayalam: "എല്ലാം",
    bengali: "সব",
    gujarati: "બધા",
    marathi: "सर्व",
    punjabi: "ਸਾਰੇ",
    odia: "ସବୁ",
    nepali: "सबै",
  },
  good_morning: {
    telugu: "శుభోదయం",
    hindi: "सुप्रभात",
    tamil: "இனிய காலை",
    kannada: "ಶುಭೋದಯ",
    malayalam: "ശുഭോദയം",
    bengali: "সুপ্রভাত",
    gujarati: "સુપ્રભાત",
    marathi: "शुभ प्रभात",
    punjabi: "ਸ਼ੁਭ ਸਵੇਰ",
    odia: "ସୁପ୍ରଭାତ",
    nepali: "शुभ प्रभात",
  },
  good_afternoon: {
    telugu: "శుభ మధ్యాహ్నం",
    hindi: "शुभ दोपहर",
    tamil: "இனிய மதியம்",
    kannada: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    malayalam: "ശുഭ ഉച്ചക്ക്",
    bengali: "শুভ দুপুর",
    gujarati: "શુભ બપોર",
    marathi: "शुभ दुपार",
    punjabi: "ਸ਼ੁਭ ਦੁਪਹਿਰ",
    odia: "ଶୁଭ ମଧ୍ୟାହ୍ନ",
    nepali: "शुभ दिउँसो",
  },
  good_night: {
    telugu: "శుభ రాత్రి",
    hindi: "शुभ रात्रि",
    tamil: "இனிய இரவு",
    kannada: "ಶುಭ ರಾತ್ರಿ",
    malayalam: "ശുഭ രാത്രി",
    bengali: "শুভ রাত্রি",
    gujarati: "શુભ રાત્રિ",
    marathi: "शुभ रात्री",
    punjabi: "ਸ਼ੁਭ ਰਾਤ",
    odia: "ଶୁଭ ରାତ୍ରି",
    nepali: "शुभ रात्री",
  },
  motivational: {
    telugu: "ప్రేరణాత్మక",
    hindi: "प्रेरणादायक",
    tamil: "ஊக்கமளிப்பு",
    kannada: "ಪ್ರೇರಣಾದಾಯಕ",
    malayalam: "പ്രചോദനാത്മകം",
    bengali: "অনুপ্রেরণামূলক",
    gujarati: "પ્રેરણાદાયક",
    marathi: "प्रेरणादायी",
    punjabi: "ਪ੍ਰੇਰਣਾਦਾਇਕ",
    odia: "ପ୍ରେରଣାଦାୟକ",
    nepali: "प्रेरणादायी",
  },
  love_quotes: {
    telugu: "ప్రేమ సూక్తులు",
    hindi: "प्रेम उद्धरण",
    tamil: "காதல் மேற்கோள்கள்",
    kannada: "ಪ್ರೀತಿ ಉಕ್ತಿಗಳು",
    malayalam: "പ്രണയ ഉദ്ധരണികൾ",
    bengali: "ভালোবাসার উক্তি",
    gujarati: "પ્રેમ ક્વોટ્સ",
    marathi: "प्रेम विचार",
    punjabi: "ਪਿਆਰ ਦੇ ਵਿਚਾਰ",
    odia: "ପ୍ରେମ ଉକ୍ତି",
    nepali: "प्रेम उद्धरण",
  },
  today_special: {
    telugu: "నేటి ప్రత్యేకం",
    hindi: "आज का विशेष",
    tamil: "இன்றைய சிறப்பு",
    kannada: "ಇಂದಿನ ವಿಶೇಷ",
    malayalam: "ഇന്നത്തെ പ്രത്യേകത",
    bengali: "আজকের বিশেষ",
    gujarati: "આજનું ખાસ",
    marathi: "आजचे विशेष",
    punjabi: "ਅੱਜ ਦਾ ਖਾਸ",
    odia: "ଆଜିର ବିଶେଷ",
    nepali: "आजको विशेष",
  },
  birthdays: {
    telugu: "పుట్టినరోజులు",
    hindi: "जन्मदिन",
    tamil: "பிறந்தநாள்கள்",
    kannada: "ಜನ್ಮದಿನಗಳು",
    malayalam: "ജന്മദിനങ്ങൾ",
    bengali: "জন্মদিন",
    gujarati: "જન્મદિવસ",
    marathi: "वाढदिवस",
    punjabi: "ਜਨਮਦਿਨ",
    odia: "ଜନ୍ମଦିନ",
    nepali: "जन्मदिन",
  },
  life_advice: {
    telugu: "జీవిత సలహా",
    hindi: "जीवन सलाह",
    tamil: "வாழ்க்கை ஆலோசனை",
    kannada: "ಜೀವನ ಸಲಹೆ",
    malayalam: "ജീവിത ഉപദേശം",
    bengali: "জীবনের পরামর্শ",
    gujarati: "જીવન સલાહ",
    marathi: "जीवन सल्ला",
    punjabi: "ਜੀਵਨ ਸਲਾਹ",
    odia: "ଜୀବନ ପରାମର୍ଶ",
    nepali: "जीवन सल्लाह",
  },
  gita_wisdom: {
    telugu: "గీతా జ్ఞానం",
    hindi: "गीता ज्ञान",
    tamil: "கீதா ஞானம்",
    kannada: "ಗೀತಾ ಜ್ಞಾನ",
    malayalam: "ഗീതാ ജ്ഞാനം",
    bengali: "গীতার জ্ঞান",
    gujarati: "ગીતા જ્ઞાન",
    marathi: "गीता ज्ञान",
    punjabi: "ਗੀਤਾ ਗਿਆਨ",
    odia: "ଗୀତା ଜ୍ଞାନ",
    nepali: "गीता ज्ञान",
  },
  devotional: {
    telugu: "భక్తి",
    hindi: "भक्ति",
    tamil: "பக்தி",
    kannada: "ಭಕ್ತಿ",
    malayalam: "ഭക്തി",
    bengali: "ভক্তি",
    gujarati: "ભક્તિ",
    marathi: "भक्ती",
    punjabi: "ਭਗਤੀ",
    odia: "ଭକ୍ତି",
    nepali: "भक्ति",
  },
  mahabharata: {
    telugu: "మహాభారతం",
    hindi: "महाभारत",
    tamil: "மகாபாரதம்",
    kannada: "ಮಹಾಭಾರತ",
    malayalam: "മഹാഭാരതം",
    bengali: "মহাভারত",
    gujarati: "મહાભારત",
    marathi: "महाभारत",
    punjabi: "ਮਹਾਭਾਰਤ",
    odia: "ମହାଭାରତ",
    nepali: "महाभारत",
  },
  anniversary: {
    telugu: "వార్షికోత్సవం",
    hindi: "वर्षगाँठ",
    tamil: "ஆண்டு விழா",
    kannada: "ವಾರ್ಷಿಕೋತ್ಸವ",
    malayalam: "വാർഷികം",
    bengali: "বার্ষিকী",
    gujarati: "વર્ષગાંઠ",
    marathi: "वर्धापनदिन",
    punjabi: "ਵਰ੍ਹੇਗੰਢ",
    odia: "ବାର୍ଷିକୀ",
    nepali: "वार्षिकोत्सव",
  },
  good_thoughts: {
    telugu: "మంచి ఆలోచనలు",
    hindi: "अच्छे विचार",
    tamil: "நல்ல எண்ணங்கள்",
    kannada: "ಒಳ್ಳೆಯ ಆಲೋಚನೆಗಳು",
    malayalam: "നല്ല ചിന്തകൾ",
    bengali: "ভালো চিন্তা",
    gujarati: "સારા વિચારો",
    marathi: "चांगले विचार",
    punjabi: "ਚੰਗੇ ਵਿਚਾਰ",
    odia: "ଭଲ ଚିନ୍ତା",
    nepali: "राम्रा विचार",
  },
  bible: {
    telugu: "బైబిల్",
    hindi: "बाइबल",
    tamil: "பைபிள்",
    kannada: "ಬೈಬಲ್",
    malayalam: "ബൈബിൾ",
    bengali: "বাইবেল",
    gujarati: "બાઇબલ",
    marathi: "बायबल",
    punjabi: "ਬਾਈਬਲ",
    odia: "ବାଇବେଲ",
    nepali: "बाइबल",
  },
  islam: {
    telugu: "ఇస్లాం",
    hindi: "इस्लाम",
    tamil: "இஸ்லாம்",
    kannada: "ಇಸ್ಲಾಂ",
    malayalam: "ഇസ്ലാം",
    bengali: "ইসলাম",
    gujarati: "ઇસ્લામ",
    marathi: "इस्लाम",
    punjabi: "ਇਸਲਾਮ",
    odia: "ଇସ୍ଲାମ",
    nepali: "इस्लाम",
  },
  jokes: {
    telugu: "జోక్స్",
    hindi: "चुटकुले",
    tamil: "நகைச்சுவை",
    kannada: "ಜೋಕ್ಸ್",
    malayalam: "തമാശകൾ",
    bengali: "রসিকতা",
    gujarati: "જોક્સ",
    marathi: "विनोद",
    punjabi: "ਚੁਟਕਲੇ",
    odia: "ହସକଥା",
    nepali: "चुटकिला",
  },
  new: {
    telugu: "మరిన్ని",
    hindi: "और",
    tamil: "மேலும்",
    kannada: "ಇನ್ನಷ್ಟು",
    malayalam: "കൂടുതൽ",
    bengali: "আরও",
    gujarati: "વધુ",
    marathi: "अधिक",
    punjabi: "ਹੋਰ",
    odia: "ଅଧିକ",
    nepali: "थप",
  },
};

export function localizeCategoryLabel(
  category: CategoryLike,
  regionOrId?: unknown,
): string {
  void CATEGORY_LABELS[category.id];
  void regionOrId;
  return categoryLabelWithIcon(category.id, category.label);
}

export function localizeCategoryList<T extends CategoryLike>(
  categories: T[],
  regionOrId?: DashboardRegion | string | null,
): T[] {
  return categories.map((item) => ({
    ...item,
    label: localizeCategoryLabel(item, regionOrId),
  }));
}
