import { DashboardRegionLanguage, getDashboardRegion } from "@/lib/dashboard-regions";

export interface PoliticalPartyCategory {
  id: string;
  partyId: string;
  label: string;
  shortName: string;
  regionIds: string[];
}

export const POLITICAL_PARTY_CATEGORIES: PoliticalPartyCategory[] = [
  { id: "party_bjp", partyId: "bjp", label: "Bharatiya Janata Party", shortName: "BJP", regionIds: [] },
  { id: "party_inc", partyId: "inc", label: "Indian National Congress", shortName: "INC", regionIds: [] },
  { id: "party_aap", partyId: "aap", label: "Aam Aadmi Party", shortName: "AAP", regionIds: [] },
  { id: "party_bsp", partyId: "bsp", label: "Bahujan Samaj Party", shortName: "BSP", regionIds: [] },
  { id: "party_cpi_m", partyId: "cpi_m", label: "Communist Party of India (Marxist)", shortName: "CPI(M)", regionIds: [] },
  { id: "party_cpi", partyId: "cpi", label: "Communist Party of India", shortName: "CPI", regionIds: [] },
  { id: "party_npp", partyId: "npp", label: "National People's Party", shortName: "NPP", regionIds: [] },
  { id: "party_tdp", partyId: "tdp", label: "Telugu Desam Party", shortName: "TDP", regionIds: ["andhra_pradesh", "telangana"] },
  { id: "party_ysrcp", partyId: "ysrcp", label: "YSR Congress Party", shortName: "YSRCP", regionIds: ["andhra_pradesh"] },
  { id: "party_brs", partyId: "brs", label: "Bharat Rashtra Samithi", shortName: "BRS", regionIds: ["telangana"] },
  { id: "party_aitc", partyId: "aitc", label: "All India Trinamool Congress", shortName: "AITC", regionIds: ["west_bengal", "tripura", "meghalaya"] },
  { id: "party_dmk", partyId: "dmk", label: "Dravida Munnetra Kazhagam", shortName: "DMK", regionIds: ["tamil_nadu", "puducherry"] },
  { id: "party_aiadmk", partyId: "aiadmk", label: "All India Anna Dravida Munnetra Kazhagam", shortName: "AIADMK", regionIds: ["tamil_nadu", "puducherry"] },
  { id: "party_jds", partyId: "jds", label: "Janata Dal (Secular)", shortName: "JD(S)", regionIds: ["karnataka"] },
  { id: "party_shiv_sena", partyId: "shiv_sena", label: "Shiv Sena", shortName: "SS", regionIds: ["maharashtra"] },
  { id: "party_ncp", partyId: "ncp", label: "Nationalist Congress Party", shortName: "NCP", regionIds: ["maharashtra"] },
  { id: "party_rjd", partyId: "rjd", label: "Rashtriya Janata Dal", shortName: "RJD", regionIds: ["bihar", "jharkhand"] },
  { id: "party_jdu", partyId: "jdu", label: "Janata Dal (United)", shortName: "JD(U)", regionIds: ["bihar"] },
  { id: "party_sp", partyId: "sp", label: "Samajwadi Party", shortName: "SP", regionIds: ["uttar_pradesh", "uttarakhand"] },
  { id: "party_rld", partyId: "rld", label: "Rashtriya Lok Dal", shortName: "RLD", regionIds: ["uttar_pradesh"] },
  { id: "party_sad", partyId: "sad", label: "Shiromani Akali Dal", shortName: "SAD", regionIds: ["punjab", "chandigarh"] },
  { id: "party_bjd", partyId: "bjd", label: "Biju Janata Dal", shortName: "BJD", regionIds: ["odisha"] },
  { id: "party_jmm", partyId: "jmm", label: "Jharkhand Mukti Morcha", shortName: "JMM", regionIds: ["jharkhand"] },
  { id: "party_skm", partyId: "skm", label: "Sikkim Krantikari Morcha", shortName: "SKM", regionIds: ["sikkim"] },
  { id: "party_mnf", partyId: "mnf", label: "Mizo National Front", shortName: "MNF", regionIds: ["mizoram"] },
  { id: "party_npf", partyId: "npf", label: "Naga People's Front", shortName: "NPF", regionIds: ["nagaland", "manipur"] },
  { id: "party_jknc", partyId: "jknc", label: "National Conference", shortName: "JKNC", regionIds: ["jammu_kashmir", "ladakh"] },
  { id: "party_pdp", partyId: "pdp", label: "Peoples Democratic Party", shortName: "PDP", regionIds: ["jammu_kashmir"] },
  { id: "party_agp", partyId: "agp", label: "Asom Gana Parishad", shortName: "AGP", regionIds: ["assam"] },
  { id: "party_udp", partyId: "udp", label: "United Democratic Party", shortName: "UDP", regionIds: ["meghalaya"] },
  { id: "party_tmp", partyId: "tmp", label: "Tipra Motha Party", shortName: "TMP", regionIds: ["tripura"] },
  { id: "party_mgp", partyId: "mgp", label: "Maharashtrawadi Gomantak Party", shortName: "MGP", regionIds: ["goa"] },
  { id: "party_inld", partyId: "inld", label: "Indian National Lok Dal", shortName: "INLD", regionIds: ["haryana"] },
  { id: "party_jjp", partyId: "jjp", label: "Jannayak Janta Party", shortName: "JJP", regionIds: ["haryana"] },
  { id: "party_aifb", partyId: "aifb", label: "All India Forward Bloc", shortName: "AIFB", regionIds: ["west_bengal"] },
  { id: "party_rsp", partyId: "rsp", label: "Revolutionary Socialist Party", shortName: "RSP", regionIds: ["kerala", "west_bengal", "tripura"] },
  { id: "party_iuml", partyId: "iuml", label: "Indian Union Muslim League", shortName: "IUML", regionIds: ["kerala"] },
  { id: "party_kc_m", partyId: "kc_m", label: "Kerala Congress (M)", shortName: "KC(M)", regionIds: ["kerala"] },
  { id: "party_kc", partyId: "kc", label: "Kerala Congress", shortName: "KC", regionIds: ["kerala"] },
  { id: "party_cpi_ml_l", partyId: "cpi_ml_l", label: "Communist Party of India (Marxist-Leninist) Liberation", shortName: "CPI(ML)L", regionIds: ["bihar"] },
  { id: "party_aimim", partyId: "aimim", label: "All India Majlis-e-Ittehadul Muslimeen", shortName: "AIMIM", regionIds: ["telangana", "maharashtra"] },
  { id: "party_ajsupa", partyId: "ajsupa", label: "AJSU Party", shortName: "AJSU", regionIds: ["jharkhand"] },
  { id: "party_ad_s", partyId: "ad_s", label: "Apna Dal (Soneylal)", shortName: "AD(S)", regionIds: ["uttar_pradesh"] },
  { id: "party_ljp_rv", partyId: "ljp_rv", label: "Lok Janshakti Party (Ram Vilas)", shortName: "LJP(RV)", regionIds: ["bihar"] },
  { id: "party_rljp", partyId: "rljp", label: "Rashtriya Lok Janshakti Party", shortName: "RLJP", regionIds: ["bihar"] },
  { id: "party_ham_s", partyId: "ham_s", label: "Hindustani Awam Morcha (Secular)", shortName: "HAM(S)", regionIds: ["bihar"] },
  { id: "party_vip", partyId: "vip", label: "Vikassheel Insaan Party", shortName: "VIP", regionIds: ["bihar"] },
  { id: "party_jsp", partyId: "jsp", label: "Jana Sena Party", shortName: "JSP", regionIds: ["andhra_pradesh", "telangana"] },
  { id: "party_ntk", partyId: "ntk", label: "Naam Tamilar Katchi", shortName: "NTK", regionIds: ["tamil_nadu", "puducherry"] },
  { id: "party_pmk", partyId: "pmk", label: "Pattali Makkal Katchi", shortName: "PMK", regionIds: ["tamil_nadu", "puducherry"] },
  { id: "party_vck", partyId: "vck", label: "Viduthalai Chiruthaigal Katchi", shortName: "VCK", regionIds: ["tamil_nadu", "puducherry"] },
  { id: "party_mdmk", partyId: "mdmk", label: "Marumalarchi Dravida Munnetra Kazhagam", shortName: "MDMK", regionIds: ["tamil_nadu"] },
  { id: "party_dmdk", partyId: "dmdk", label: "Desiya Murpokku Dravida Kazhagam", shortName: "DMDK", regionIds: ["tamil_nadu"] },
  { id: "party_aiudf", partyId: "aiudf", label: "All India United Democratic Front", shortName: "AIUDF", regionIds: ["assam"] },
  { id: "party_bpf", partyId: "bpf", label: "Bodoland People's Front", shortName: "BPF", regionIds: ["assam"] },
  { id: "party_uppl", partyId: "uppl", label: "United People's Party Liberal", shortName: "UPPL", regionIds: ["assam"] },
  { id: "party_zpm", partyId: "zpm", label: "Zoram People's Movement", shortName: "ZPM", regionIds: ["mizoram"] },
  { id: "party_ndpp", partyId: "ndpp", label: "Nationalist Democratic Progressive Party", shortName: "NDPP", regionIds: ["nagaland"] },
  { id: "party_ipft", partyId: "ipft", label: "Indigenous People's Front of Tripura", shortName: "IPFT", regionIds: ["tripura"] },
  { id: "party_rgp", partyId: "rgp", label: "Revolutionary Goans Party", shortName: "RGP", regionIds: ["goa"] },
  { id: "party_gfp", partyId: "gfp", label: "Goa Forward Party", shortName: "GFP", regionIds: ["goa"] },
  { id: "party_hspdp", partyId: "hspdp", label: "Hill State People's Democratic Party", shortName: "HSPDP", regionIds: ["meghalaya"] },
  { id: "party_vpp", partyId: "vpp", label: "Voice of the People Party", shortName: "VPP", regionIds: ["meghalaya"] },
  { id: "party_ppa", partyId: "ppa", label: "People's Party of Arunachal", shortName: "PPA", regionIds: ["arunachal_pradesh"] },
  { id: "party_bap", partyId: "bap", label: "Bharat Adivasi Party", shortName: "BAP", regionIds: ["rajasthan"] },
  { id: "party_rpi_a", partyId: "rpi_a", label: "Republican Party of India (A)", shortName: "RPI(A)", regionIds: ["maharashtra"] },
  { id: "party_mns", partyId: "mns", label: "Maharashtra Navnirman Sena", shortName: "MNS", regionIds: ["maharashtra"] },
  { id: "party_swabhimani", partyId: "swabhimani", label: "Swabhimani Paksha", shortName: "SWP", regionIds: ["maharashtra"] },
  { id: "party_prahar", partyId: "prahar", label: "Prahar Janshakti Party", shortName: "PJP", regionIds: ["maharashtra"] },
  { id: "party_sdf", partyId: "sdf", label: "Sikkim Democratic Front", shortName: "SDF", regionIds: ["sikkim"] },
  { id: "party_rlp", partyId: "rlp", label: "Rashtriya Loktantrik Party", shortName: "RLP", regionIds: ["rajasthan"] },
  { id: "party_sbsp", partyId: "sbsp", label: "Suheldev Bharatiya Samaj Party", shortName: "SBSP", regionIds: ["uttar_pradesh"] },
  { id: "party_ncp_sp", partyId: "ncp_sp", label: "Nationalist Congress Party - Sharadchandra Pawar", shortName: "NCP(SP)", regionIds: ["maharashtra", "nagaland"] },
  { id: "party_shs_ubt", partyId: "shs_ubt", label: "Shiv Sena (Uddhav Balasaheb Thackeray)", shortName: "SHS(UBT)", regionIds: ["maharashtra"] },
  { id: "party_jkpc", partyId: "jkpc", label: "Jammu and Kashmir People's Conference", shortName: "JKPC", regionIds: ["jammu_kashmir"] },
  { id: "party_kpa", partyId: "kpa", label: "Kuki People's Alliance", shortName: "KPA", regionIds: ["manipur"] },
  { id: "party_ukd", partyId: "ukd", label: "Uttarakhand Kranti Dal", shortName: "UKD", regionIds: ["uttarakhand"] },
  { id: "party_jccj", partyId: "jccj", label: "Janta Congress Chhattisgarh (J)", shortName: "JCC(J)", regionIds: ["chhattisgarh"] },
  { id: "party_tvk", partyId: "tvk", label: "Tamilaga Vettri Kazhagam", shortName: "TVK", regionIds: ["tamil_nadu", "puducherry"] },
  { id: "party_tmc_m", partyId: "tmc_m", label: "Tamil Maanila Congress (Moopanar)", shortName: "TMC(M)", regionIds: ["tamil_nadu"] },
  { id: "party_vba", partyId: "vba", label: "Vanchit Bahujan Aaghadi", shortName: "VBA", regionIds: ["maharashtra"] },
  { id: "party_wpi", partyId: "wpi", label: "Welfare Party of India", shortName: "WPI", regionIds: ["kerala"] },
  { id: "party_jsdl", partyId: "jsdl", label: "Jansatta Dal (Loktantrik)", shortName: "JSDL", regionIds: ["uttar_pradesh"] },
];

export const POLITICAL_PARTY_CATEGORY_IDS = new Set(
  POLITICAL_PARTY_CATEGORIES.map((item) => item.id),
);

export const POLITICAL_PARTY_LABELS: Record<string, Partial<Record<DashboardRegionLanguage, string>>> = {
  party_bjp: { telugu: "భారతీయ జనతా పార్టీ", hindi: "भारतीय जनता पार्टी", tamil: "பாரதிய ஜனதா கட்சி", kannada: "ಭಾರತೀಯ ಜನತಾ ಪಕ್ಷ", malayalam: "ഭാരതീയ ജനതാ പാർട്ടി" },
  party_inc: { telugu: "భారత జాతీయ కాంగ్రెస్", hindi: "भारतीय राष्ट्रीय कांग्रेस", tamil: "இந்திய தேசிய காங்கிரஸ்", kannada: "ಭಾರತೀಯ ರಾಷ್ಟ್ರೀಯ ಕಾಂಗ್ರೆಸ್", malayalam: "ഇന്ത്യൻ നാഷണൽ കോൺഗ്രസ്" },
  party_aap: { telugu: "ఆమ్ ఆద్మీ పార్టీ", hindi: "आम आदमी पार्टी", tamil: "ஆம் ஆத்மி கட்சி", kannada: "ಆಮ್ ಆದ್ಮಿ ಪಕ್ಷ", malayalam: "ആം ആദ്മി പാർട്ടി" },
  party_bsp: { telugu: "బహుజన్ సమాజ్ పార్టీ", hindi: "बहुजन समाज पार्टी", tamil: "பகுஜன் சமாஜ் கட்சி", kannada: "ಬಹುಜನ ಸಮಾಜ ಪಕ್ಷ", malayalam: "ബഹുജൻ സമാജ് പാർട്ടി" },
  party_cpi_m: { telugu: "భారత కమ్యూనిస్టు పార్టీ (మార్క్సిస్టు)", hindi: "भारतीय कम्युनिस्ट पार्टी (मार्क्सवादी)", malayalam: "കമ്മ്യൂണിസ്റ്റ് പാർട്ടി ഓഫ് ഇന്ത്യ (മാർക്സിസ്റ്റ്)" },
  party_cpi: { telugu: "భారత కమ్యూనిస్టు పార్టీ", hindi: "भारतीय कम्युनिस्ट पार्टी", tamil: "இந்திய கம்யூனிஸ்ட் கட்சி", kannada: "ಭಾರತ ಕಮ್ಯುನಿಸ್ಟ್ ಪಕ್ಷ", malayalam: "കമ്മ്യൂണിസ്റ്റ് പാർട്ടി ഓഫ് ഇന്ത്യ", bengali: "ভারতীয় কমিউনিস্ট পার্টি" },
  party_npp: { telugu: "నేషనల్ పీపుల్స్ పార్టీ", hindi: "नेशनल पीपुल्स पार्टी" },
  party_tdp: { telugu: "తెలుగు దేశం పార్టీ", hindi: "तेलुगु देशम पार्टी", tamil: "தெலுங்கு தேசம் கட்சி", kannada: "ತೆಲುಗು ದೇಶಂ ಪಕ್ಷ", malayalam: "തെലുങ്കു ദേശം പാർട്ടി" },
  party_ysrcp: { telugu: "వైఎస్ఆర్ కాంగ్రెస్ పార్టీ", hindi: "वाईएसआर कांग्रेस पार्टी", tamil: "ஒய்எஸ்ஆர் காங்கிரஸ் கட்சி", kannada: "ವೈಎಸ್‌ಆರ್ ಕಾಂಗ್ರೆಸ್ ಪಕ್ಷ", malayalam: "വൈഎസ്ആർ കോൺഗ്രസ് പാർട്ടി" },
  party_brs: { telugu: "భారత్ రాష్ట్ర సమితి", hindi: "भारत राष्ट्र समिति", tamil: "பாரத் ராஷ்ட்ர சமிதி", kannada: "ಭಾರತ್ ರಾಷ್ಟ್ರ ಸಮಿತಿ", malayalam: "ഭാരത് രാഷ്ട്ര സമിതി" },
  party_aitc: { telugu: "ఆల్ ఇండియా తృణమూల్ కాంగ్రెస్", hindi: "ऑल इंडिया तृणमूल कांग्रेस", bengali: "সর্বভারতীয় তৃণমূল কংগ্রেস" },
  party_dmk: { telugu: "ద్రావిడ మున్నేత్ర కళగం", tamil: "திராவிட முன்னேற்றக் கழகம்" },
  party_aiadmk: { telugu: "ఆల్ ఇండియా అన్నా ద్రావిడ మున్నేత్ర కళగం", tamil: "அனைத்திந்திய அண்ணா திராவிட முன்னேற்றக் கழகம்" },
  party_jds: { telugu: "జనతా దళ్ (సెక్యులర్)", hindi: "जनता दल (सेक्युलर)", kannada: "ಜನತಾ ದಳ (ಜಾತ್ಯತೀತ)" },
  party_shiv_sena: { telugu: "శివసేన", hindi: "शिवसेना", marathi: "शिवसेना" },
  party_ncp: { telugu: "నేషనలిస్ట్ కాంగ్రెస్ పార్టీ", hindi: "राष्ट्रवादी कांग्रेस पार्टी", marathi: "राष्ट्रवादी काँग्रेस पक्ष" },
  party_rjd: { telugu: "రాష్ట్రీయ జనతా దళ్", hindi: "राष्ट्रीय जनता दल" },
  party_jdu: { telugu: "జనతా దళ్ (యునైటెడ్)", hindi: "जनता दल (यूनाइटेड)" },
  party_sp: { telugu: "సమాజ్‌వాది పార్టీ", hindi: "समाजवादी पार्टी" },
  party_rld: { telugu: "రాష్ట్రీయ లోక్ దళ్", hindi: "राष्ट्रीय लोक दल" },
  party_sad: { telugu: "శిరోమణి అకాలీ దళ్", hindi: "शिरोमणि अकाली दल", punjabi: "ਸ਼੍ਰੋਮਣੀ ਅਕਾਲੀ ਦਲ" },
  party_bjd: { telugu: "బిజూ జనతా దళ్", hindi: "बीजू जनता दल", odia: "ବିଜୁ ଜନତା ଦଳ" },
  party_jmm: { telugu: "జార్ఖండ్ ముక్తి మోర్చా", hindi: "झारखंड मुक्ति मोर्चा" },
  party_skm: { telugu: "సిక్కిం క్రాంతికారి మోర్చా", hindi: "सिक्किम क्रांतिकारी मोर्चा", nepali: "सिक्किम क्रान्तिकारी मोर्चा" },
  party_mnf: { telugu: "మిజో నేషనల్ ఫ్రంట్", hindi: "मिजो नेशनल फ्रंट", mizo: "Mizo National Front" },
  party_npf: { telugu: "నాగా పీపుల్స్ ఫ్రంట్", hindi: "नागा पीपुल्स फ्रंट" },
  party_jknc: { telugu: "నేషనల్ కాన్ఫరెన్స్", hindi: "नेशनल कॉन्फ्रेंस" },
  party_pdp: { telugu: "పీపుల్స్ డెమోక్రటిక్ పార్టీ", hindi: "पीपुल्स डेमोक्रेटिक पार्टी" },
  party_agp: { telugu: "అసోం గణ పరిషద్", hindi: "असम गण परिषद", assamese: "অসম গণ পৰিষদ" },
  party_udp: { telugu: "యునైటెడ్ డెమోక్రటిక్ పార్టీ", hindi: "यूनाइटेड डेमोक्रेटिक पार्टी" },
  party_tmp: { telugu: "టిప్రా మోతా పార్టీ", hindi: "टिपरा मोथा पार्टी", bengali: "টিপ্রা মথা পার্টি" },
  party_mgp: { telugu: "మహారాష్ట్రవాది గోమంతక్ పార్టీ", hindi: "महाराष्ट्रवादी गोमांतक पार्टी", konkani: "महाराष्ट्रवादी गोमंतक पक्ष" },
  party_inld: { telugu: "ఇండియన్ నేషనల్ లోక్ దళ్", hindi: "इंडियन नेशनल लोक दल" },
  party_jjp: { telugu: "జననాయక్ జనతా పార్టీ", hindi: "जननायक जनता पार्टी" },
};

export function politicalPartyCategoriesForRegion(regionId?: string | null): PoliticalPartyCategory[] {
  const region = getDashboardRegion(regionId);
  return POLITICAL_PARTY_CATEGORIES.filter(
    (party) => party.regionIds.length === 0 || party.regionIds.includes(region.id),
  );
}
