export interface ResolvedEventDateDef {
  month: number;
  day: number;
  endMonth?: number;
  endDay?: number;
  durationDays?: number;
}

export const RESOLVED_LUNAR_EVENT_DATES: Record<number, Record<string, ResolvedEventDateDef>> = {
  2026: {
    additional_day_durga_puja_west_bengal: { month: 10, day: 22, endMonth: 10, endDay: 24 },
    additional_day_kali_puja_west_bengal: { month: 11, day: 9, endMonth: 11, endDay: 10 },
    additional_day_lakshmi_puja_west_bengal: { month: 10, day: 26 },
    agrasen_jayanti_chhattisgarh: { month: 10, day: 11 },
    akheri_chahar_sumba_tripura: { month: 8, day: 12 },
    akshaya_tritiya: { month: 5, day: 9 },
    anjaneya_swamy_jayanti_usage: { month: 4, day: 2 },
    arbayeen_chahallum: { month: 8, day: 4 },
    atla_taddi: { month: 10, day: 28 },
    babu_jagjivan_ram_jayanthi: { month: 4, day: 5 },
    bakrid_eid_ul_adha: { month: 5, day: 27 },
    basanti_puja_tripura: { month: 3, day: 25 },
    basava_jayanti: { month: 4, day: 20 },
    bathukamma: { month: 10, day: 12, durationDays: 9 },
    bathukamma_starting_day: { month: 10, day: 10 },
    bhadrachalam_sri_rama_kalyanam: { month: 3, day: 27 },
    bhai_dooj: { month: 10, day: 31 },
    bhakt_mata_karma_jayanti_chhattisgarh: { month: 3, day: 15 },
    bhishma_ekadashi: { month: 2, day: 28 },
    bhogali_bihu: { month: 1, day: 14 },
    bhogi: { month: 1, day: 14 },
    biju_buisu_festival_tripura: { month: 4, day: 14 },
    birthday_hazrath_syed_mohammed_juvanpuri: { month: 10, day: 26 },
    birthday_kazi_nazrul_islam_tripura: { month: 5, day: 26 },
    bonalu: { month: 7, day: 19, durationDays: 23 },
    buddha_purnima: { month: 5, day: 1 },
    chaitra_pournami: { month: 4, day: 2 },
    chhath_puja: { month: 11, day: 3 },
    dasara_vijayadashami: { month: 10, day: 20 },
    datta_jayanthi: { month: 12, day: 23 },
    deepavali: { month: 11, day: 8 },
    dev_diwali: { month: 11, day: 24 },
    devotional_karthika_masam_start_usage: { month: 10, day: 31 },
    dhol_gyaras_chhattisgarh: { month: 9, day: 22 },
    dr_b_r_ambedkar_jayanthi: { month: 4, day: 14 },
    durga_puja_west_bengal: { month: 10, day: 17, endMonth: 10, endDay: 24 },
    eid_e_ghadeer: { month: 6, day: 4 },
    eid_ul_fitr_ramzan: { month: 3, day: 21 },
    fathers_day: { month: 6, day: 21 },
    first_onam_kerala: { month: 8, day: 25 },
    following_day_of_ramzan: { month: 3, day: 22 },
    following_day_of_vijaya_dasami: { month: 10, day: 21 },
    fourth_onam_kerala: { month: 8, day: 28 },
    friendship_day: { month: 8, day: 2 },
    garia_puja: { month: 4, day: 21 },
    good_friday: { month: 4, day: 3 },
    guru_gobind_singh_jayanti: { month: 1, day: 5 },
    guru_nanak_jayanti: { month: 11, day: 24 },
    guru_pournima: { month: 7, day: 29 },
    hanuman_jayanthi: { month: 4, day: 2 },
    harchhath_chhattisgarh: { month: 9, day: 2 },
    hareli: { month: 8, day: 12 },
    holi: { month: 3, day: 4 },
    holika_dahan_holi_eve_usage: { month: 3, day: 21 },
    hul_diwas_west_bengal: { month: 6, day: 30 },
    indigenous_faith_day_arunachal: { month: 12, day: 1 },
    jamai_sasthi_tripura: { month: 6, day: 20 },
    jamatul_vida: { month: 3, day: 13 },
    jhulan_jatra_samapan_tripura: { month: 8, day: 28 },
    kali_puja_west_bengal: { month: 11, day: 8, endMonth: 11, endDay: 10 },
    kanaka_durga_temple_dasara: { month: 9, day: 22, endMonth: 10, endDay: 2 },
    kanuma: { month: 1, day: 16 },
    karkidaka_vavu: { month: 8, day: 12 },
    karthika_pournami_karthika_deepam: { month: 11, day: 24 },
    karwa_chauth: { month: 10, day: 29 },
    ker_puja: { month: 8, day: 4 },
    kharchi_puja: { month: 7, day: 22 },
    krishna_janmashtami: { month: 9, day: 4 },
    kubera_puja: { month: 11, day: 6 },
    maa_shakambhri_jayanti_cherchera_chhattisgarh: { month: 1, day: 3 },
    maha_shivaratri: { month: 2, day: 15 },
    mahalaya_amavasya: { month: 10, day: 10 },
    maharaja_bir_bikram_jayanthi_tripura: { month: 8, day: 19 },
    mahavir_jayanti: { month: 3, day: 31 },
    makara_sankranti: { month: 1, day: 15 },
    milad_un_nabi: { month: 8, day: 26 },
    mothers_day: { month: 5, day: 10 },
    muharram_ashura: { month: 6, day: 26 },
    naga_panchami: { month: 8, day: 17 },
    nagoba_jatara: { month: 1, day: 18, durationDays: 9 },
    namdev_jayanti_chhattisgarh: { month: 11, day: 20 },
    naraka_chaturdasi: { month: 10, day: 28 },
    narasimha_jayanthi: { month: 4, day: 30 },
    nawa_khai_chhattisgarh: { month: 9, day: 18 },
    onam: { month: 8, day: 26 },
    peerla_panduga_usage: { month: 6, day: 16 },
    poet_bhanu_bhakt_jayanthi_west_bengal: { month: 7, day: 13 },
    pola_chhattisgarh: { month: 9, day: 10 },
    polala_amma_vratam: { month: 9, day: 11 },
    pous_parban_tripura: { month: 1, day: 14 },
    raksha_bandhan_sravana_purnima: { month: 8, day: 18 },
    rath_yatra: { month: 7, day: 16 },
    ratha_saptami: { month: 1, day: 25 },
    saddula_bathukamma_maha_saptami: { month: 10, day: 18 },
    sahastrabahu_jayanti_chhattisgarh: { month: 11, day: 16 },
    sammakka_saralamma_jatara_medaram_jatara: { month: 1, day: 28, durationDays: 4 },
    saraswati_puja_west_bengal: { month: 1, day: 23 },
    sarv_pitru_moksha_amavasya_chhattisgarh: { month: 10, day: 10 },
    shab_e_barat: { month: 2, day: 4 },
    shab_e_meraj: { month: 1, day: 17 },
    shab_e_qadar: { month: 3, day: 17 },
    shahadat_hazrath_ali: { month: 3, day: 10 },
    shahid_vir_narayan_singh_balidan_diwas_chhattisgarh: { month: 12, day: 10 },
    shri_shri_harichand_thakur_jayanthi_west_bengal: { month: 3, day: 17 },
    simhachalam_chandanotsavam: { month: 4, day: 20 },
    songrongma_puja_tripura: { month: 9, day: 11 },
    sri_narasimha_jayanti_usage: { month: 4, day: 30 },
    sri_panchami_vasanth_panchami: { month: 1, day: 23 },
    sri_rama_navami: { month: 3, day: 27 },
    sri_ramanavami_sita_rama_kalyanam_usage: { month: 3, day: 27 },
    srisailam_maha_shivaratri_brahmotsavam: { month: 2, day: 27, endMonth: 3, endDay: 9, durationDays: 11 },
    st_theresa_festival_puducherry: { month: 10, day: 15 },
    thakur_panchanan_barma_jayanthi_west_bengal: { month: 2, day: 14 },
    third_onam_kerala: { month: 8, day: 27 },
    thiruvalluvar_day_mattu_pongal_puducherry: { month: 1, day: 16 },
    tirumala_brahmotsavam: { month: 9, day: 15, durationDays: 9 },
    tulasi_vivaham: { month: 11, day: 21 },
    tyagaraja_aradhana: { month: 1, day: 19, durationDays: 7 },
    ugadi: { month: 3, day: 19 },
    ugadi_panchanga_sravanam: { month: 3, day: 19 },
    vaikuntha_ekadashi: { month: 12, day: 20 },
    valmiki_jayanti: { month: 10, day: 26 },
    varalakshmi_vratham: { month: 8, day: 21 },
    vinayaka_chavithi: { month: 9, day: 14 },
    vishu: { month: 4, day: 15 },
    vishva_adivasi_diwas_chhattisgarh: { month: 8, day: 9 },
    viswakarma_puja_west_bengal: { month: 9, day: 17 },
    world_first_aid_day: { month: 9, day: 12 },
    world_habitat_day: { month: 10, day: 5 },
    world_laughter_day: { month: 5, day: 3 },
    world_pangolin_day: { month: 2, day: 21 },
    world_river_day: { month: 9, day: 27 },
    yadadri_brahmotsavam: { month: 3, day: 18, durationDays: 11 },
    yaz_dahum_shareef: { month: 9, day: 23 },
  },
};
