export interface CatalogCategoryDef {
  id: string;
  label: string;
  regionIds?: string[];
}

export interface DynamicEventCategoryDef extends CatalogCategoryDef {
  month: number;
  day: number;
  durationDays?: number;
  regionIds?: string[];
}

export interface FloatingDynamicEventCategoryDef extends CatalogCategoryDef {
  month: number;
  weekOfMonth: number;
  weekdayOfMonth: number;
  durationDays?: number;
}

export const CSV_FIXED_DYNAMIC_EVENT_CATEGORIES: DynamicEventCategoryDef[] = [
  { id: 'bhogi', label: 'Bhogi', month: 1, day: 13, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kanuma', label: 'Kanuma', month: 1, day: 15, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'mukkanuma', label: 'Mukkanuma', month: 1, day: 16, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'christmas', label: 'Christmas', month: 12, day: 25, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'yogi_vemana_jayanthi', label: 'Yogi Vemana Jayanthi', month: 1, day: 19, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'n_t_rama_rao_vardhanthi', label: 'N.T. Rama Rao Vardhanthi', month: 1, day: 18, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'damodaram_sanjivayya_jayanthi', label: 'Damodaram Sanjivayya Jayanthi', month: 2, day: 14, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'potti_sreeramulu_jayanthi', label: 'Potti Sreeramulu Jayanthi', month: 3, day: 16, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kandukuri_veeresalingam_jayanthi', label: 'Kandukuri Veeresalingam Jayanthi', month: 4, day: 16, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'n_t_rama_rao_jayanthi', label: 'N.T. Rama Rao Jayanthi', month: 5, day: 28, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kandukuri_veeresalingam_vardhanthi', label: 'Kandukuri Veeresalingam Vardhanthi', month: 5, day: 27, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'alluri_sitarama_raju_jayanthi', label: 'Alluri Sitarama Raju Jayanthi', month: 7, day: 4, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'y_s_rajasekhara_reddy_jayanthi', label: 'Y.S. Rajasekhara Reddy Jayanthi', month: 7, day: 8, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'tanguturi_prakasam_panthulu_jayanthi', label: 'Tanguturi Prakasam Panthulu Jayanthi', month: 8, day: 23, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'gurajada_apparao_jayanthi', label: 'Gurajada Apparao Jayanthi', month: 9, day: 21, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'y_s_rajasekhara_reddy_vardhanthi', label: 'Y.S. Rajasekhara Reddy Vardhanthi', month: 9, day: 2, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'andhra_state_formation_day', label: 'Andhra State Formation Day', month: 10, day: 1, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'potti_sreeramulu_vardhanthi_atmarpana_dinotsavam', label: 'Potti Sreeramulu Vardhanthi / Atmarpana Dinotsavam', month: 12, day: 15, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'andhra_pradesh_formation_day', label: 'Andhra Pradesh Formation Day', month: 11, day: 1, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'viswakarma_jayanthi', label: 'Viswakarma Jayanthi', month: 9, day: 17, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'damodaram_sanjivayya_vardhanthi', label: 'Damodaram Sanjivayya Vardhanthi', month: 5, day: 7, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'gurajada_apparao_vardhanthi', label: 'Gurajada Apparao Vardhanthi', month: 11, day: 30, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'sant_sevalal_maharaj_jayanthi', label: 'Sant Sevalal Maharaj Jayanthi', month: 2, day: 15, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'komaram_bheem_vardhanthi', label: 'Komaram Bheem Vardhanthi', month: 10, day: 7, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'telangana_formation_day', label: 'Telangana Formation Day', month: 6, day: 2, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'p_v_narasimha_rao_jayanthi', label: 'P.V. Narasimha Rao Jayanthi', month: 6, day: 28, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'prof_kothapalli_jayashankar_jayanthi', label: 'Prof. Kothapalli Jayashankar Jayanthi', month: 8, day: 6, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kaloji_narayana_rao_jayanthi', label: 'Kaloji Narayana Rao Jayanthi', month: 9, day: 9, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'chityala_ilamma_vardhanthi', label: 'Chityala Ilamma Vardhanthi', month: 9, day: 10, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'praja_palana_dinotsavam', label: 'Praja Palana Dinotsavam', month: 9, day: 17, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'komaram_bheem_jayanthi', label: 'Komaram Bheem Jayanthi', month: 10, day: 22, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'p_v_narasimha_rao_vardhanthi', label: 'P.V. Narasimha Rao Vardhanthi', month: 12, day: 23, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kaloji_narayana_rao_vardhanthi', label: 'Kaloji Narayana Rao Vardhanthi', month: 11, day: 13, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'telangana_liberation_integration_memory_day_usage_variants', label: 'Telangana Liberation / Integration memory day usage variants', month: 9, day: 17, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'swami_vivekananda_jayanthi', label: 'Swami Vivekananda Jayanthi', month: 1, day: 12 },
  { id: 'netaji_subhas_chandra_bose_jayanthi', label: 'Netaji Subhas Chandra Bose Jayanthi', month: 1, day: 23 },
  { id: 'lala_lajpat_rai_jayanthi', label: 'Lala Lajpat Rai Jayanthi', month: 1, day: 28 },
  { id: 'swami_dayananda_saraswati_jayanthi', label: 'Swami Dayananda Saraswati Jayanthi', month: 2, day: 12 },
  { id: 'chhatrapati_shivaji_maharaj_jayanthi', label: 'Chhatrapati Shivaji Maharaj Jayanthi', month: 2, day: 19 },
  { id: 'sarojini_naidu_jayanthi', label: 'Sarojini Naidu Jayanthi', month: 2, day: 13 },
  { id: 'babu_jagjivan_ram_jayanthi', label: 'Babu Jagjivan Ram Jayanthi', month: 4, day: 5 },
  { id: 'dr_b_r_ambedkar_jayanthi', label: 'Dr. B.R. Ambedkar Jayanthi', month: 4, day: 14 },
  { id: 'rabindranath_tagore_jayanthi', label: 'Rabindranath Tagore Jayanthi', month: 5, day: 7 },
  { id: 'veer_savarkar_jayanthi', label: 'Veer Savarkar Jayanthi', month: 5, day: 28 },
  { id: 'jawaharlal_nehru_jayanthi', label: 'Jawaharlal Nehru Jayanthi', month: 11, day: 14 },
  { id: 'rajiv_gandhi_jayanthi_sadbhavana_diwas', label: 'Rajiv Gandhi Jayanthi / Sadbhavana Diwas', month: 8, day: 20 },
  { id: 'mangal_pandey_jayanthi', label: 'Mangal Pandey Jayanthi', month: 7, day: 19 },
  { id: 'bal_gangadhar_tilak_jayanthi', label: 'Bal Gangadhar Tilak Jayanthi', month: 7, day: 23 },
  { id: 'chandrashekhar_azad_jayanthi', label: 'Chandrashekhar Azad Jayanthi', month: 7, day: 23 },
  { id: 'dr_sarvepalli_radhakrishnan_jayanthi', label: 'Dr. Sarvepalli Radhakrishnan Jayanthi', month: 9, day: 5 },
  { id: 'bhagat_singh_jayanthi', label: 'Bhagat Singh Jayanthi', month: 9, day: 28 },
  { id: 'mahatma_gandhi_jayanthi', label: 'Mahatma Gandhi Jayanthi', month: 10, day: 2 },
  { id: 'lal_bahadur_shastri_jayanthi', label: 'Lal Bahadur Shastri Jayanthi', month: 10, day: 2 },
  { id: 'sardar_vallabhbhai_patel_jayanthi', label: 'Sardar Vallabhbhai Patel Jayanthi', month: 10, day: 31 },
  { id: 'rani_lakshmibai_jayanthi', label: 'Rani Lakshmibai Jayanthi', month: 11, day: 19 },
  { id: 'indira_gandhi_jayanthi', label: 'Indira Gandhi Jayanthi', month: 11, day: 19 },
  { id: 'birsa_munda_jayanthi_janjatiya_gaurav_divas', label: 'Birsa Munda Jayanthi / Janjatiya Gaurav Divas', month: 11, day: 15 },
  { id: 'a_p_j_abdul_kalam_jayanthi', label: 'A.P.J. Abdul Kalam Jayanthi', month: 10, day: 15 },
  { id: 'lal_bahadur_shastri_vardhanthi', label: 'Lal Bahadur Shastri Vardhanthi', month: 1, day: 11 },
  { id: 'mahatma_gandhi_vardhanthi_martyrs_day', label: 'Mahatma Gandhi Vardhanthi / Martyrs’ Day', month: 1, day: 30 },
  { id: 'chhatrapati_shivaji_maharaj_vardhanthi', label: 'Chhatrapati Shivaji Maharaj Vardhanthi', month: 4, day: 3 },
  { id: 'dr_b_r_ambedkar_vardhanthi_mahaparinirvan_diwas', label: 'Dr. B.R. Ambedkar Vardhanthi / Mahaparinirvan Diwas', month: 12, day: 6 },
  { id: 'shaheed_diwas_bhagat_singh_rajguru_sukhdev', label: 'Shaheed Diwas (Bhagat Singh, Rajguru, Sukhdev)', month: 3, day: 23 },
  { id: 'jawaharlal_nehru_vardhanthi', label: 'Jawaharlal Nehru Vardhanthi', month: 5, day: 27 },
  { id: 'rajiv_gandhi_vardhanthi_anti_terrorism_day', label: 'Rajiv Gandhi Vardhanthi / Anti-Terrorism Day', month: 5, day: 21 },
  { id: 'babu_jagjivan_ram_vardhanthi', label: 'Babu Jagjivan Ram Vardhanthi', month: 7, day: 6 },
  { id: 'a_p_j_abdul_kalam_vardhanthi', label: 'A.P.J. Abdul Kalam Vardhanthi', month: 7, day: 27 },
  { id: 'subhas_chandra_bose_vardhanthi', label: 'Subhas Chandra Bose Vardhanthi', month: 8, day: 18 },
  { id: 'vinoba_bhave_vardhanthi', label: 'Vinoba Bhave Vardhanthi', month: 11, day: 15 },
  { id: 'indira_gandhi_vardhanthi', label: 'Indira Gandhi Vardhanthi', month: 10, day: 31 },
  { id: 'sardar_vallabhbhai_patel_vardhanthi', label: 'Sardar Vallabhbhai Patel Vardhanthi', month: 12, day: 15 },
  { id: 'rabindranath_tagore_vardhanthi', label: 'Rabindranath Tagore Vardhanthi', month: 8, day: 7 },
  { id: 'national_youth_day', label: 'National Youth Day', month: 1, day: 12 },
  { id: 'army_day', label: 'Army Day', month: 1, day: 15 },
  { id: 'national_girl_child_day', label: 'National Girl Child Day', month: 1, day: 24 },
  { id: 'national_voters_day', label: 'National Voters’ Day', month: 1, day: 25 },
  { id: 'republic_day', label: 'Republic Day', month: 1, day: 26 },
  { id: 'martyrs_day', label: 'Martyrs’ Day', month: 1, day: 30 },
  { id: 'national_science_day', label: 'National Science Day', month: 2, day: 28 },
  { id: 'international_women_s_day', label: 'International Women’s Day', month: 3, day: 8 },
  { id: 'world_water_day', label: 'World Water Day', month: 3, day: 22 },
  { id: 'world_health_day', label: 'World Health Day', month: 4, day: 7 },
  { id: 'national_civil_services_day', label: 'National Civil Services Day', month: 4, day: 21 },
  { id: 'labour_day_may_day', label: 'Labour Day / May Day', month: 5, day: 1 },
  { id: 'national_technology_day', label: 'National Technology Day', month: 5, day: 11 },
  { id: 'world_environment_day', label: 'World Environment Day', month: 6, day: 5 },
  { id: 'international_yoga_day', label: 'International Yoga Day', month: 6, day: 21 },
  { id: 'national_doctors_day', label: 'National Doctors’ Day', month: 7, day: 1 },
  { id: 'kargil_vijay_diwas', label: 'Kargil Vijay Diwas', month: 7, day: 26 },
  { id: 'independence_day', label: 'Independence Day', month: 8, day: 15 },
  { id: 'national_sports_day', label: 'National Sports Day', month: 8, day: 29 },
  { id: 'teachers_day', label: 'Teachers’ Day', month: 9, day: 5 },
  { id: 'hindi_diwas', label: 'Hindi Diwas', month: 9, day: 14 },
  { id: 'gandhi_jayanti_international_day_of_non_violence', label: 'Gandhi Jayanti / International Day of Non-Violence', month: 10, day: 2 },
  { id: 'national_unity_day', label: 'National Unity Day', month: 10, day: 31 },
  { id: 'constitution_day_samvidhan_divas', label: 'Constitution Day / Samvidhan Divas', month: 11, day: 26 },
  { id: 'national_education_day', label: 'National Education Day', month: 11, day: 11 },
  { id: 'children_s_day', label: 'Children’s Day', month: 11, day: 14 },
  { id: 'armed_forces_flag_day', label: 'Armed Forces Flag Day', month: 12, day: 7 },
  { id: 'kisan_diwas_national_farmers_day', label: 'Kisan Diwas / National Farmers’ Day', month: 12, day: 23 },
  { id: 'good_governance_day', label: 'Good Governance Day', month: 12, day: 25 },
  { id: 'sri_krishnadevaraya_jayanthi', label: 'Sri Krishnadevaraya Jayanthi', month: 1, day: 17, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'nara_lokesh_birthday', label: 'Nara Lokesh Birthday', month: 1, day: 23, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'n_chandrababu_naidu_birthday', label: 'N. Chandrababu Naidu Birthday', month: 4, day: 20, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kodela_siva_prasada_rao_jayanthi', label: 'Kodela Siva Prasada Rao Jayanthi', month: 5, day: 2, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'puchalapalli_sundarayya_jayanthi', label: 'Puchalapalli Sundarayya Jayanthi', month: 5, day: 1, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'annamacharya_jayanthi', label: 'Annamacharya Jayanthi', month: 5, day: 9, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'tyagaraja_jayanthi', label: 'Tyagaraja Jayanthi', month: 5, day: 4, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'pawan_kalyan_birthday', label: 'Pawan Kalyan Birthday', month: 9, day: 2, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'vangaveeti_mohana_ranga_vardhanthi', label: 'Vangaveeti Mohana Ranga Vardhanthi', month: 12, day: 26, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kodela_siva_prasada_rao_vardhanthi', label: 'Kodela Siva Prasada Rao Vardhanthi', month: 9, day: 16, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'puchalapalli_sundarayya_vardhanthi', label: 'Puchalapalli Sundarayya Vardhanthi', month: 5, day: 19, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'annamacharya_vardhanthi', label: 'Annamacharya Vardhanthi', month: 2, day: 23, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'k_chandrashekar_rao_birthday', label: 'K. Chandrashekar Rao Birthday', month: 2, day: 17, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'burgula_ramakrishna_rao_jayanthi', label: 'Burgula Ramakrishna Rao Jayanthi', month: 3, day: 13, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'ravi_narayana_reddy_jayanthi', label: 'Ravi Narayana Reddy Jayanthi', month: 6, day: 4, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'k_t_rama_rao_birthday', label: 'K.T. Rama Rao Birthday', month: 7, day: 24, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'dasarathi_krishnamacharyulu_jayanthi', label: 'Dasarathi Krishnamacharyulu Jayanthi', month: 7, day: 22, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'a_revanth_reddy_birthday', label: 'A. Revanth Reddy Birthday', month: 11, day: 8, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'suravaram_pratap_reddy_jayanthi', label: 'Suravaram Pratap Reddy Jayanthi', month: 5, day: 28, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'konda_laxman_bapuji_jayanthi', label: 'Konda Laxman Bapuji Jayanthi', month: 9, day: 27, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'marri_chenna_reddy_jayanthi', label: 'Marri Chenna Reddy Jayanthi', month: 1, day: 13, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'burgula_ramakrishna_rao_vardhanthi', label: 'Burgula Ramakrishna Rao Vardhanthi', month: 9, day: 15, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'ravi_narayana_reddy_vardhanthi', label: 'Ravi Narayana Reddy Vardhanthi', month: 9, day: 7, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'dasarathi_krishnamacharyulu_vardhanthi', label: 'Dasarathi Krishnamacharyulu Vardhanthi', month: 11, day: 5, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'suravaram_pratap_reddy_vardhanthi', label: 'Suravaram Pratap Reddy Vardhanthi', month: 8, day: 25, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'konda_laxman_bapuji_vardhanthi', label: 'Konda Laxman Bapuji Vardhanthi', month: 9, day: 21, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'marri_chenna_reddy_vardhanthi', label: 'Marri Chenna Reddy Vardhanthi', month: 12, day: 2, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'savitribai_phule_jayanthi', label: 'Savitribai Phule Jayanthi', month: 1, day: 3, regionIds: ['maharashtra'] },
  { id: 'kalpana_chawla_jayanthi', label: 'Kalpana Chawla Jayanthi', month: 3, day: 17, regionIds: ['haryana'] },
  { id: 'ram_manohar_lohia_jayanthi', label: 'Ram Manohar Lohia Jayanthi', month: 3, day: 23, regionIds: ['uttar_pradesh'] },
  { id: 'jyotirao_phule_jayanthi', label: 'Jyotirao Phule Jayanthi', month: 4, day: 11 },
  { id: 'syama_prasad_mookerjee_jayanthi', label: 'Syama Prasad Mookerjee Jayanthi', month: 7, day: 6 },
  { id: 'vikram_sarabhai_jayanthi', label: 'Vikram Sarabhai Jayanthi', month: 8, day: 12 },
  { id: 'm_s_swaminathan_jayanthi', label: 'M.S. Swaminathan Jayanthi', month: 8, day: 7 },
  { id: 'periyar_e_v_ramasamy_jayanthi', label: 'Periyar E.V. Ramasamy Jayanthi', month: 9, day: 17 },
  { id: 'deendayal_upadhyaya_jayanthi', label: 'Deendayal Upadhyaya Jayanthi', month: 9, day: 25, regionIds: ['uttar_pradesh'] },
  { id: 'homi_j_bhabha_jayanthi', label: 'Homi J. Bhabha Jayanthi', month: 10, day: 30 },
  { id: 'dhyan_chand_jayanthi', label: 'Dhyan Chand Jayanthi', month: 8, day: 29 },
  { id: 'madan_mohan_malaviya_jayanthi', label: 'Madan Mohan Malaviya Jayanthi', month: 12, day: 25 },
  { id: 'atal_bihari_vajpayee_jayanthi', label: 'Atal Bihari Vajpayee Jayanthi', month: 12, day: 25, regionIds: ['uttar_pradesh'] },
  { id: 'udham_singh_jayanthi', label: 'Udham Singh Jayanthi', month: 12, day: 26 },
  { id: 'savitribai_phule_vardhanthi', label: 'Savitribai Phule Vardhanthi', month: 3, day: 10 },
  { id: 'kalpana_chawla_vardhanthi', label: 'Kalpana Chawla Vardhanthi', month: 2, day: 1 },
  { id: 'deendayal_upadhyaya_vardhanthi', label: 'Deendayal Upadhyaya Vardhanthi', month: 2, day: 11 },
  { id: 'homi_j_bhabha_vardhanthi', label: 'Homi J. Bhabha Vardhanthi', month: 1, day: 24 },
  { id: 'jyotirao_phule_vardhanthi', label: 'Jyotirao Phule Vardhanthi', month: 11, day: 28 },
  { id: 'syama_prasad_mookerjee_vardhanthi', label: 'Syama Prasad Mookerjee Vardhanthi', month: 6, day: 23 },
  { id: 'vikram_sarabhai_vardhanthi', label: 'Vikram Sarabhai Vardhanthi', month: 12, day: 30 },
  { id: 'dhyan_chand_vardhanthi', label: 'Dhyan Chand Vardhanthi', month: 12, day: 3 },
  { id: 'm_s_swaminathan_vardhanthi', label: 'M.S. Swaminathan Vardhanthi', month: 9, day: 28 },
  { id: 'periyar_e_v_ramasamy_vardhanthi', label: 'Periyar E.V. Ramasamy Vardhanthi', month: 12, day: 24 },
  { id: 'ram_manohar_lohia_vardhanthi', label: 'Ram Manohar Lohia Vardhanthi', month: 10, day: 12 },
  { id: 'atal_bihari_vajpayee_vardhanthi', label: 'Atal Bihari Vajpayee Vardhanthi', month: 8, day: 16, regionIds: ['uttar_pradesh'] },
  { id: 'sushma_swaraj_jayanthi', label: 'Sushma Swaraj Jayanthi', month: 2, day: 14 },
  { id: 'sushma_swaraj_vardhanthi', label: 'Sushma Swaraj Vardhanthi', month: 8, day: 6 },
  { id: 'madan_mohan_malaviya_vardhanthi', label: 'Madan Mohan Malaviya Vardhanthi', month: 11, day: 12 },
  { id: 'udham_singh_vardhanthi', label: 'Udham Singh Vardhanthi', month: 7, day: 31 },
  { id: 'national_mathematics_day', label: 'National Mathematics Day', month: 12, day: 22 },
  { id: 'national_handloom_day', label: 'National Handloom Day', month: 8, day: 7 },
  { id: 'national_legal_services_day', label: 'National Legal Services Day', month: 11, day: 9 },
  { id: 'national_maritime_day', label: 'National Maritime Day', month: 4, day: 5 },
  { id: 'national_unity_day_run_for_unity_use_case', label: 'National Unity Day (Run for Unity use-case)', month: 10, day: 31 },
  { id: 'y_s_jagan_mohan_reddy_birthday', label: 'Y.S. Jagan Mohan Reddy Birthday', month: 12, day: 21, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'nandamuri_balakrishna_birthday', label: 'Nandamuri Balakrishna Birthday', month: 6, day: 10, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'akkineni_nageswara_rao_jayanthi', label: 'Akkineni Nageswara Rao Jayanthi', month: 9, day: 20, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'akkineni_nageswara_rao_vardhanthi', label: 'Akkineni Nageswara Rao Vardhanthi', month: 1, day: 22, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'nandamuri_taraka_rama_rao_jr_birthday', label: 'Nandamuri Taraka Rama Rao Jr. Birthday', month: 5, day: 20, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 's_v_ranga_rao_jayanthi', label: 'S. V. Ranga Rao Jayanthi', month: 7, day: 3, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 's_v_ranga_rao_vardhanthi', label: 'S. V. Ranga Rao Vardhanthi', month: 7, day: 18, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'gummadi_venkateswara_rao_jayanthi', label: 'Gummadi Venkateswara Rao Jayanthi', month: 7, day: 9, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'gummadi_venkateswara_rao_vardhanthi', label: 'Gummadi Venkateswara Rao Vardhanthi', month: 1, day: 26, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'krishnam_raju_jayanthi', label: 'Krishnam Raju Jayanthi', month: 1, day: 20, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'krishnam_raju_vardhanthi', label: 'Krishnam Raju Vardhanthi', month: 9, day: 11, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'sobhan_babu_jayanthi', label: 'Sobhan Babu Jayanthi', month: 1, day: 14, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'sobhan_babu_vardhanthi', label: 'Sobhan Babu Vardhanthi', month: 3, day: 20, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'bhanumathi_ramakrishna_jayanthi', label: 'Bhanumathi Ramakrishna Jayanthi', month: 9, day: 7, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'bhanumathi_ramakrishna_vardhanthi', label: 'Bhanumathi Ramakrishna Vardhanthi', month: 12, day: 24, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kasinadhuni_nageswara_rao_pantulu_jayanthi', label: 'Kasinadhuni Nageswara Rao Pantulu Jayanthi', month: 5, day: 1, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kasinadhuni_nageswara_rao_pantulu_vardhanthi', label: 'Kasinadhuni Nageswara Rao Pantulu Vardhanthi', month: 4, day: 11, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'tenneti_viswanadham_jayanthi', label: 'Tenneti Viswanadham Jayanthi', month: 7, day: 9, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'tenneti_viswanadham_vardhanthi', label: 'Tenneti Viswanadham Vardhanthi', month: 11, day: 10, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'gouthu_latchanna_jayanthi', label: 'Gouthu Latchanna Jayanthi', month: 8, day: 16, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'gouthu_latchanna_vardhanthi', label: 'Gouthu Latchanna Vardhanthi', month: 4, day: 19, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'pingali_venkayya_jayanthi', label: 'Pingali Venkayya Jayanthi', month: 8, day: 2, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'pingali_venkayya_vardhanthi', label: 'Pingali Venkayya Vardhanthi', month: 7, day: 4, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'sri_potti_sriramulu_andhra_state_day_memory_usage', label: 'Sri Potti Sriramulu Andhra State Day memory usage', month: 10, day: 1, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'sri_annamayya_jayanthi', label: 'Sri Annamayya Jayanthi', month: 5, day: 9, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'sri_annamayya_vardhanthi', label: 'Sri Annamayya Vardhanthi', month: 2, day: 23, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'kaloji_narayana_rao_telangana_language_day_usage', label: 'Kaloji Narayana Rao Telangana Language Day usage', month: 9, day: 9, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'dasarathi_rangacharya_jayanthi', label: 'Dasarathi Rangacharya Jayanthi', month: 8, day: 24, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'dasarathi_rangacharya_vardhanthi', label: 'Dasarathi Rangacharya Vardhanthi', month: 6, day: 8, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'c_narayana_reddy_jayanthi', label: 'C. Narayana Reddy Jayanthi', month: 7, day: 29, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'c_narayana_reddy_vardhanthi', label: 'C. Narayana Reddy Vardhanthi', month: 6, day: 12, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'chakali_ailamma_jayanthi', label: 'Chakali Ailamma Jayanthi', month: 9, day: 26, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'chakali_ailamma_vardhanthi', label: 'Chakali Ailamma Vardhanthi', month: 9, day: 10, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'baddam_yella_reddy_jayanthi', label: 'Baddam Yella Reddy Jayanthi', month: 10, day: 9, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'baddam_yella_reddy_vardhanthi', label: 'Baddam Yella Reddy Vardhanthi', month: 2, day: 9, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'ramji_gond_jayanthi', label: 'Ramji Gond Jayanthi', month: 4, day: 1, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'ramji_gond_vardhanthi', label: 'Ramji Gond Vardhanthi', month: 4, day: 9, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'shoebullah_khan_jayanthi', label: 'Shoebullah Khan Jayanthi', month: 10, day: 16, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'shoebullah_khan_vardhanthi', label: 'Shoebullah Khan Vardhanthi', month: 8, day: 22, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'savarkar_vardhanthi', label: 'Savarkar Vardhanthi', month: 2, day: 26 },
  { id: 'dr_rajendra_prasad_jayanthi', label: 'Dr. Rajendra Prasad Jayanthi', month: 12, day: 3, regionIds: ['bihar'] },
  { id: 'dr_rajendra_prasad_vardhanthi', label: 'Dr. Rajendra Prasad Vardhanthi', month: 2, day: 28 },
  { id: 'sardar_bhagat_singh_martyrdom_remembrance_usage', label: 'Sardar Bhagat Singh Martyrdom remembrance usage', month: 3, day: 23 },
  { id: 'lalaji_vardhanthi', label: 'Lalaji Vardhanthi', month: 11, day: 17 },
  { id: 'madan_lal_dhingra_jayanthi', label: 'Madan Lal Dhingra Jayanthi', month: 2, day: 18 },
  { id: 'madan_lal_dhingra_vardhanthi', label: 'Madan Lal Dhingra Vardhanthi', month: 8, day: 17 },
  { id: 'sukhdev_thapar_jayanthi', label: 'Sukhdev Thapar Jayanthi', month: 5, day: 15 },
  { id: 'rajguru_jayanthi', label: 'Rajguru Jayanthi', month: 8, day: 24 },
  { id: 'rash_behari_bose_jayanthi', label: 'Rash Behari Bose Jayanthi', month: 5, day: 25 },
  { id: 'rash_behari_bose_vardhanthi', label: 'Rash Behari Bose Vardhanthi', month: 1, day: 21 },
  { id: 'mangal_pandey_vardhanthi', label: 'Mangal Pandey Vardhanthi', month: 4, day: 8 },
  { id: 'chandrashekhar_azad_vardhanthi', label: 'Chandrashekhar Azad Vardhanthi', month: 2, day: 27 },
  { id: 'bal_gangadhar_tilak_vardhanthi', label: 'Bal Gangadhar Tilak Vardhanthi', month: 8, day: 1, regionIds: ['maharashtra'] },
  { id: 'sardar_udham_singh_martyrdom_remembrance_usage', label: 'Sardar Udham Singh Martyrdom remembrance usage', month: 7, day: 31 },
  { id: 'dr_zakir_husain_jayanthi', label: 'Dr. Zakir Husain Jayanthi', month: 2, day: 8 },
  { id: 'dr_zakir_husain_vardhanthi', label: 'Dr. Zakir Husain Vardhanthi', month: 5, day: 3 },
  { id: 'a_p_j_abdul_kalam_world_students_day_linkage', label: 'A.P.J. Abdul Kalam World Students Day linkage', month: 10, day: 15 },
  { id: 'national_space_day', label: 'National Space Day', month: 8, day: 23 },
  { id: 'national_startup_day', label: 'National Startup Day', month: 1, day: 16 },
  { id: 'national_press_day', label: 'National Press Day', month: 11, day: 16 },
  { id: 'national_energy_conservation_day', label: 'National Energy Conservation Day', month: 12, day: 14 },
  { id: 'national_consumer_rights_day', label: 'National Consumer Rights Day', month: 12, day: 24 },
  { id: 'national_pollution_control_day', label: 'National Pollution Control Day', month: 12, day: 2 },
  { id: 'world_literacy_day', label: 'World Literacy Day', month: 9, day: 8 },
  { id: 'national_nutrition_week_start_usage', label: 'National Nutrition Week start usage', month: 9, day: 1 },
  { id: 'national_unity_week_start_usage', label: 'National Unity Week start usage', month: 10, day: 31 },
  { id: 'sardar_patel_national_unity_day_campaign_use', label: 'Sardar Patel National Unity Day campaign use', month: 10, day: 31 },
  { id: 'satyajit_ray_jayanthi', label: 'Satyajit Ray Jayanthi', month: 5, day: 2 },
  { id: 'satyajit_ray_vardhanthi', label: 'Satyajit Ray Vardhanthi', month: 4, day: 23 },
  { id: 'dadasaheb_phalke_jayanthi', label: 'Dadasaheb Phalke Jayanthi', month: 4, day: 30 },
  { id: 'dadasaheb_phalke_vardhanthi', label: 'Dadasaheb Phalke Vardhanthi', month: 2, day: 16 },
  { id: 'lata_mangeshkar_jayanthi', label: 'Lata Mangeshkar Jayanthi', month: 9, day: 28 },
  { id: 'lata_mangeshkar_vardhanthi', label: 'Lata Mangeshkar Vardhanthi', month: 2, day: 6 },
  { id: 'bhimsen_joshi_jayanthi', label: 'Bhimsen Joshi Jayanthi', month: 2, day: 4 },
  { id: 'bhimsen_joshi_vardhanthi', label: 'Bhimsen Joshi Vardhanthi', month: 1, day: 24 },
  { id: 'sri_sri_jayanthi', label: 'Sri Sri Jayanthi', month: 4, day: 30, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'sri_sri_vardhanthi', label: 'Sri Sri Vardhanthi', month: 6, day: 15, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'gurram_jashuva_jayanthi', label: 'Gurram Jashuva Jayanthi', month: 9, day: 28, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'gurram_jashuva_vardhanthi', label: 'Gurram Jashuva Vardhanthi', month: 7, day: 24, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'viswanatha_satyanarayana_jayanthi', label: 'Viswanatha Satyanarayana Jayanthi', month: 9, day: 10, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'viswanatha_satyanarayana_vardhanthi', label: 'Viswanatha Satyanarayana Vardhanthi', month: 10, day: 18, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'tripuraneni_ramaswamy_jayanthi', label: 'Tripuraneni Ramaswamy Jayanthi', month: 1, day: 15, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'tripuraneni_ramaswamy_vardhanthi', label: 'Tripuraneni Ramaswamy Vardhanthi', month: 1, day: 16, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'rayaprolu_subba_rao_jayanthi', label: 'Rayaprolu Subba Rao Jayanthi', month: 3, day: 8, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'rayaprolu_subba_rao_vardhanthi', label: 'Rayaprolu Subba Rao Vardhanthi', month: 6, day: 30, regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'national_petroleum_day', label: 'National Petroleum Day', month: 1, day: 9 },
  { id: 'world_poetry_day', label: 'World Poetry Day', month: 3, day: 21 },
  { id: 'world_creativity_and_innovation_day', label: 'World Creativity and Innovation Day', month: 4, day: 21 },
  { id: 'international_dance_day', label: 'International Dance Day', month: 4, day: 29 },
  { id: 'world_telecommunications_day', label: 'World Telecommunication Day', month: 5, day: 17 },
  { id: 'world_social_media_day', label: 'World Social Media Day', month: 6, day: 30 },
  { id: 'world_music_day', label: 'World Music Day', month: 6, day: 21 },
  { id: 'world_skill_day', label: 'World Youth Skills Day', month: 7, day: 15 },
  { id: 'national_library_day', label: 'National Library Day', month: 8, day: 12 },
  { id: 'world_elephant_day', label: 'World Elephant Day', month: 8, day: 12 },
  { id: 'world_senior_citizens_day', label: 'World Senior Citizens Day', month: 8, day: 21 },
  { id: 'national_media_day', label: 'National Media Day', month: 9, day: 16 },
  { id: 'world_heart_day', label: 'World Heart Day', month: 9, day: 29 },
  { id: 'world_post_day', label: 'World Post Day', month: 10, day: 9 },
  { id: 'world_diabetes_day', label: 'World Diabetes Day', month: 11, day: 14 },
  { id: 'world_children_day', label: 'World Children’s Day', month: 11, day: 20 },
  { id: 'christmas_eve', label: 'Christmas Eve', month: 12, day: 24 },
  { id: 'christmas_new_year_week', label: 'Christmas New Year Week Celebrations', month: 12, day: 26, durationDays: 6 },
  { id: 'world_hepatitis_day', label: 'World Hepatitis Day', month: 7, day: 28 },
  { id: 'world_rabies_day', label: 'World Rabies Day', month: 9, day: 28 },
  { id: 'international_day_of_older_persons', label: 'International Day of Older Persons', month: 10, day: 1 },
  { id: 'road_safety_week', label: 'National Road Safety Week', month: 1, day: 11, durationDays: 7 },
  { id: 'international_customs_day', label: 'International Customs Day', month: 1, day: 26 },
  { id: 'world_sparrow_day', label: 'World Sparrow Day', month: 3, day: 20 },
  { id: 'fire_service_day', label: 'National Fire Service Day', month: 4, day: 14 },
  { id: 'world_bee_day', label: 'World Bee Day', month: 5, day: 20 },
  { id: 'international_day_of_yoga_for_women_usage', label: 'Women Yoga Awareness Day Usage', month: 6, day: 21 },
  { id: 'world_food_safety_day', label: 'World Food Safety Day', month: 6, day: 7 },
  { id: 'world_nature_conservation_day', label: 'World Nature Conservation Day', month: 7, day: 28 },
  { id: 'world_mosquito_day', label: 'World Mosquito Day', month: 8, day: 20 },
  { id: 'world_suicide_prevention_day', label: 'World Suicide Prevention Day', month: 9, day: 10 },
  { id: 'world_stroke_day', label: 'World Stroke Day', month: 10, day: 29 },
  { id: 'national_epilepsy_day', label: 'National Epilepsy Day', month: 11, day: 17 },
  { id: 'world_hindu_council_day', label: 'World Hindu Council Day', month: 8, day: 29 },
  { id: 'birthday_hazrath_syed_mohammed_juvanpuri', label: 'Hazrath Syed Mohammed Juvanpuri Jayanthi', month: 10, day: 26 },
  { id: 'hrithik_roshan_birthday', label: 'Hrithik Roshan Birthday', month: 1, day: 10 },
  { id: 'deepika_padukone_birthday', label: 'Deepika Padukone Birthday', month: 1, day: 5 },
  { id: 'a_r_rahman_birthday', label: 'A.R. Rahman Birthday', month: 1, day: 6 },
  { id: 'shreya_ghoshal_birthday', label: 'Shreya Ghoshal Birthday', month: 3, day: 12 },
  { id: 'aamir_khan_birthday', label: 'Aamir Khan Birthday', month: 3, day: 14 },
  { id: 'alia_bhatt_birthday', label: 'Alia Bhatt Birthday', month: 3, day: 15 },
  { id: 'saina_nehwal_birthday', label: 'Saina Nehwal Birthday', month: 3, day: 17 },
  { id: 'sachin_tendulkar_birthday', label: 'Sachin Tendulkar Birthday', month: 4, day: 24 },
  { id: 'rohit_sharma_birthday', label: 'Rohit Sharma Birthday', month: 4, day: 30 },
  { id: 'madhuri_dixit_birthday', label: 'Madhuri Dixit Birthday', month: 5, day: 15 },
  { id: 'p_v_sindhu_birthday', label: 'P.V. Sindhu Birthday', month: 7, day: 5 },
  { id: 'm_s_dhoni_birthday', label: 'M.S. Dhoni Birthday', month: 7, day: 7 },
  { id: 'priyanka_chopra_birthday', label: 'Priyanka Chopra Birthday', month: 7, day: 18 },
  { id: 'akshay_kumar_birthday', label: 'Akshay Kumar Birthday', month: 9, day: 9 },
  { id: 'ranbir_kapoor_birthday', label: 'Ranbir Kapoor Birthday', month: 9, day: 28 },
  { id: 'amitabh_bachchan_birthday', label: 'Amitabh Bachchan Birthday', month: 10, day: 11 },
  { id: 'shah_rukh_khan_birthday', label: 'Shah Rukh Khan Birthday', month: 11, day: 2 },
  { id: 'virat_kohli_birthday', label: 'Virat Kohli Birthday', month: 11, day: 5 },
  { id: 'mary_kom_birthday', label: 'Mary Kom Birthday', month: 11, day: 24 },
  { id: 'neeraj_chopra_birthday', label: 'Neeraj Chopra Birthday', month: 12, day: 24 },
  { id: 'salman_khan_birthday', label: 'Salman Khan Birthday', month: 12, day: 27 },
  { id: 'narendra_modi_birthday', label: 'Narendra Modi Birthday', month: 9, day: 17 },
  { id: 'amit_shah_birthday', label: 'Amit Shah Birthday', month: 10, day: 22 },
  { id: 'rahul_gandhi_birthday', label: 'Rahul Gandhi Birthday', month: 6, day: 19 },
  { id: 'mamata_banerjee_birthday', label: 'Mamata Banerjee Birthday', month: 1, day: 5 },
  { id: 'm_k_stalin_birthday', label: 'M.K. Stalin Birthday', month: 3, day: 1 },
  { id: 'yogi_adityanath_birthday', label: 'Yogi Adityanath Birthday', month: 6, day: 5 },
  { id: 'arvind_kejriwal_birthday', label: 'Arvind Kejriwal Birthday', month: 8, day: 16 },
  { id: 'nitish_kumar_birthday', label: 'Nitish Kumar Birthday', month: 3, day: 1 },
  { id: 'naveen_patnaik_birthday', label: 'Naveen Patnaik Birthday', month: 10, day: 16 },
  { id: 'himanta_biswa_sarma_birthday', label: 'Himanta Biswa Sarma Birthday', month: 2, day: 1 },
  { id: 'kapil_dev_birthday', label: 'Kapil Dev Birthday', month: 1, day: 6 },
  { id: 'sunil_gavaskar_birthday', label: 'Sunil Gavaskar Birthday', month: 7, day: 10 },
  { id: 'rahul_dravid_birthday', label: 'Rahul Dravid Birthday', month: 1, day: 11 },
  { id: 'sourav_ganguly_birthday', label: 'Sourav Ganguly Birthday', month: 7, day: 8 },
  { id: 'yuvraj_singh_birthday', label: 'Yuvraj Singh Birthday', month: 12, day: 12 },
  { id: 'sania_mirza_birthday', label: 'Sania Mirza Birthday', month: 11, day: 15 },
  { id: 'abhinav_bindra_birthday', label: 'Abhinav Bindra Birthday', month: 9, day: 28 },
  { id: 'mirabai_chanu_birthday', label: 'Mirabai Chanu Birthday', month: 8, day: 8 },
  { id: 'ranveer_singh_birthday', label: 'Ranveer Singh Birthday', month: 7, day: 6 },
  { id: 'kareena_kapoor_khan_birthday', label: 'Kareena Kapoor Khan Birthday', month: 9, day: 21 },
  { id: 'katrina_kaif_birthday', label: 'Katrina Kaif Birthday', month: 7, day: 16 },
  { id: 'anushka_sharma_birthday', label: 'Anushka Sharma Birthday', month: 5, day: 1 },
  { id: 'varun_dhawan_birthday', label: 'Varun Dhawan Birthday', month: 4, day: 24 },
  { id: 'kartik_aaryan_birthday', label: 'Kartik Aaryan Birthday', month: 11, day: 22 },
];

export const CSV_FLOATING_DYNAMIC_EVENT_CATEGORIES: FloatingDynamicEventCategoryDef[] = [
  { id: 'mothers_day', label: 'Mother\'s Day', month: 5, weekOfMonth: 2, weekdayOfMonth: 0 },
  { id: 'fathers_day', label: 'Father\'s Day', month: 6, weekOfMonth: 3, weekdayOfMonth: 0 },
  { id: 'friendship_day', label: 'Friendship Day', month: 8, weekOfMonth: 1, weekdayOfMonth: 0 },
  { id: 'world_laughter_day', label: 'World Laughter Day', month: 5, weekOfMonth: 1, weekdayOfMonth: 0 },
  { id: 'world_first_aid_day', label: 'World First Aid Day', month: 9, weekOfMonth: 2, weekdayOfMonth: 6 },
  { id: 'world_pangolin_day', label: 'World Pangolin Day', month: 2, weekOfMonth: 3, weekdayOfMonth: 6 },
  { id: 'world_river_day', label: 'World Rivers Day', month: 9, weekOfMonth: 4, weekdayOfMonth: 0 },
  { id: 'world_habitat_day', label: 'World Habitat Day', month: 10, weekOfMonth: 1, weekdayOfMonth: 1 },
];

export const CSV_LUNAR_PLACEHOLDER_CATEGORIES: CatalogCategoryDef[] = [
  { id: 'makara_sankranti', label: 'Makara Sankranti' },
  { id: 'ratha_saptami', label: 'Ratha Saptami' },
  { id: 'maha_shivaratri', label: 'Maha Shivaratri' },
  { id: 'holi', label: 'Holi' },
  { id: 'ugadi', label: 'Ugadi' },
  { id: 'sri_rama_navami', label: 'Sri Rama Navami' },
  { id: 'hanuman_jayanthi', label: 'Hanuman Jayanthi' },
  { id: 'narasimha_jayanthi', label: 'Narasimha Jayanthi' },
  { id: 'bonalu', label: 'Bonalu', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'varalakshmi_vratham', label: 'Varalakshmi Vratham' },
  { id: 'krishna_janmashtami', label: 'Krishna Janmashtami' },
  { id: 'vinayaka_chavithi', label: 'Vinayaka Chavithi' },
  { id: 'bathukamma', label: 'Bathukamma', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'dasara_vijayadashami', label: 'Dasara / Vijayadashami' },
  { id: 'deepavali', label: 'Deepavali' },
  { id: 'karthika_pournami_karthika_deepam', label: 'Karthika Pournami / Karthika Deepam' },
  { id: 'vaikuntha_ekadashi', label: 'Vaikuntha Ekadashi' },
  { id: 'sammakka_saralamma_jatara_medaram_jatara', label: 'Sammakka Saralamma Jatara / Medaram Jatara', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'nagoba_jatara', label: 'Nagoba Jatara', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'guru_nanak_jayanti', label: 'Guru Nanak Jayanti' },
  { id: 'tyagaraja_aradhana', label: 'Tyagaraja Aradhana' },
  { id: 'guru_gobind_singh_jayanti', label: 'Guru Gobind Singh Jayanti' },
  { id: 'basava_jayanti', label: 'Basava Jayanti' },
  { id: 'valmiki_jayanti', label: 'Valmiki Jayanti' },
  { id: 'mahavir_jayanti', label: 'Mahavir Jayanti' },
  { id: 'kanaka_durga_temple_dasara', label: 'Kanaka Durga Temple Dasara', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'tirumala_brahmotsavam', label: 'Tirumala Brahmotsavam', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'simhachalam_chandanotsavam', label: 'Simhachalam Chandanotsavam', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'srisailam_maha_shivaratri_brahmotsavam', label: 'Srisailam Maha Shivaratri Brahmotsavam', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'yadadri_brahmotsavam', label: 'Yadadri Brahmotsavam', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'bhadrachalam_sri_rama_kalyanam', label: 'Bhadrachalam Sri Rama Kalyanam', regionIds: ['andhra_pradesh', 'telangana'] },
  { id: 'peerla_panduga_usage', label: 'Peerla Panduga usage' },
  { id: 'sri_ramanavami_sita_rama_kalyanam_usage', label: 'Sri Ramanavami Sita Rama Kalyanam usage' },
  { id: 'anjaneya_swamy_jayanti_usage', label: 'Anjaneya Swamy Jayanti usage' },
  { id: 'sri_narasimha_jayanti_usage', label: 'Sri Narasimha Jayanti usage' },
  { id: 'devotional_karthika_masam_start_usage', label: 'Devotional Karthika Masam start usage' },
  { id: 'ugadi_panchanga_sravanam', label: 'Ugadi Panchanga Sravanam' },
  { id: 'polala_amma_vratam', label: 'Polala Amavasya' },
  { id: 'atla_taddi', label: 'Atla Taddi' },
  { id: 'naga_panchami', label: 'Naga Panchami' },
  { id: 'datta_jayanthi', label: 'Datta Jayanthi' },
  { id: 'guru_pournima', label: 'Guru Pournima' },
  { id: 'kubera_puja', label: 'Kubera Puja' },
  { id: 'tulasi_vivaham', label: 'Tulasi Vivaham' },
  { id: 'bhishma_ekadashi', label: 'Bhishma Ekadashi' },
  { id: 'sri_panchami_vasanth_panchami', label: 'Vasanth Panchami' },
  { id: 'chaitra_pournami', label: 'Chaitra Pournami' },
  { id: 'onam', label: 'Onam', regionIds: ['kerala'] },
  { id: 'karwa_chauth', label: 'Karwa Chauth' },
  { id: 'dev_diwali', label: 'Dev Diwali' },
];
