import type { DynamicEventCategoryDef } from "./dynamic-event-catalog";

export const REGIONAL_DYNAMIC_EVENT_CATEGORIES: DynamicEventCategoryDef[] = [
  { id: "arunachal_pradesh_statehood_day", label: "Arunachal Pradesh Statehood Day", month: 2, day: 20, regionIds: ["arunachal_pradesh"] },
  { id: "nyokum", label: "Nyokum", month: 2, day: 26, regionIds: ["arunachal_pradesh"] },
  { id: "solung", label: "Solung Festival", month: 9, day: 1, regionIds: ["arunachal_pradesh"] },
  { id: "losar_arunachal", label: "Losar", month: 2, day: 10, regionIds: ["arunachal_pradesh"] },
  { id: "assam_day_asom_divas", label: "Assam Day / Asom Divas", month: 12, day: 2, regionIds: ["assam"] },
  { id: "rongali_bihu", label: "Rongali Bihu", month: 4, day: 14, regionIds: ["assam"] },
  { id: "bhogali_bihu", label: "Bhogali Bihu", month: 1, day: 15, regionIds: ["assam"] },
  { id: "kati_bihu", label: "Kati Bihu", month: 10, day: 18, regionIds: ["assam"] },
  { id: "lachit_divas", label: "Lachit Divas", month: 11, day: 24, regionIds: ["assam"] },
  { id: "bihar_diwas", label: "Bihar Diwas", month: 3, day: 22, regionIds: ["bihar"] },
  { id: "chhath_puja_bihar", label: "Chhath Puja", month: 11, day: 7, regionIds: ["bihar"] },
  { id: "sonepur_mela", label: "Sonepur Mela", month: 11, day: 15, regionIds: ["bihar"] },
  { id: "chhattisgarh_rajyotsava", label: "Chhattisgarh Rajyotsava", month: 11, day: 1, regionIds: ["chhattisgarh"] },
  { id: "hareli", label: "Hareli", month: 7, day: 17, regionIds: ["chhattisgarh"] },
  { id: "pola_chhattisgarh", label: "Pola", month: 9, day: 2, regionIds: ["chhattisgarh"] },
  { id: "teeja_chhattisgarh", label: "Teeja", month: 9, day: 6, regionIds: ["chhattisgarh"] },
  { id: "goa_statehood_day", label: "Goa Statehood Day", month: 5, day: 30, regionIds: ["goa"] },
  { id: "goa_liberation_day", label: "Goa Liberation Day", month: 12, day: 19, regionIds: ["goa"] },
  { id: "sao_joao", label: "Sao Joao", month: 6, day: 24, regionIds: ["goa"] },
  { id: "shigmo", label: "Shigmo", month: 3, day: 15, regionIds: ["goa"] },
  { id: "gujarat_day", label: "Gujarat Day", month: 5, day: 1, regionIds: ["gujarat"] },
  { id: "uttarayan_gujarat", label: "Uttarayan", month: 1, day: 14, regionIds: ["gujarat"] },
  { id: "navratri_garba", label: "Navratri Garba", month: 10, day: 3, regionIds: ["gujarat"] },
  { id: "rann_utsav", label: "Rann Utsav", month: 11, day: 1, regionIds: ["gujarat"] },
  { id: "haryana_day", label: "Haryana Day", month: 11, day: 1, regionIds: ["haryana"] },
  { id: "surajkund_mela", label: "Surajkund Mela", month: 2, day: 1, regionIds: ["haryana"] },
  { id: "gita_jayanti_haryana", label: "Gita Jayanti", month: 12, day: 11, regionIds: ["haryana"] },
  { id: "himachal_pradesh_statehood_day", label: "Himachal Pradesh Statehood Day", month: 1, day: 25, regionIds: ["himachal_pradesh"] },
  { id: "himachal_day", label: "Himachal Day", month: 4, day: 15, regionIds: ["himachal_pradesh"] },
  { id: "minjar_mela", label: "Minjar Mela", month: 7, day: 28, regionIds: ["himachal_pradesh"] },
  { id: "kullu_dussehra", label: "Kullu Dussehra", month: 10, day: 12, regionIds: ["himachal_pradesh"] },
  { id: "jharkhand_foundation_day", label: "Jharkhand Foundation Day", month: 11, day: 15, regionIds: ["jharkhand"] },
  { id: "sarhul", label: "Sarhul", month: 4, day: 11, regionIds: ["jharkhand"] },
  { id: "karma_jharkhand", label: "Karma Festival", month: 9, day: 14, regionIds: ["jharkhand"] },
  { id: "sohrai", label: "Sohrai", month: 11, day: 1, regionIds: ["jharkhand"] },
  { id: "karnataka_rajyotsava", label: "Karnataka Rajyotsava", month: 11, day: 1, regionIds: ["karnataka"] },
  { id: "basava_jayanti_karnataka", label: "Basava Jayanti", month: 5, day: 10, regionIds: ["karnataka"] },
  { id: "kanakadasa_jayanthi", label: "Kanakadasa Jayanthi", month: 11, day: 18, regionIds: ["karnataka"] },
  { id: "mysuru_dasara", label: "Mysuru Dasara", month: 10, day: 12, regionIds: ["karnataka"] },
  { id: "kerala_piravi", label: "Kerala Piravi", month: 11, day: 1, regionIds: ["kerala"] },
  { id: "vishu", label: "Vishu", month: 4, day: 14, regionIds: ["kerala"] },
  { id: "thrissur_pooram", label: "Thrissur Pooram", month: 5, day: 7, regionIds: ["kerala"] },
  { id: "attukal_pongala", label: "Attukal Pongala", month: 3, day: 13, regionIds: ["kerala"] },
  { id: "madhya_pradesh_foundation_day", label: "Madhya Pradesh Foundation Day", month: 11, day: 1, regionIds: ["madhya_pradesh"] },
  { id: "khajuraho_dance_festival", label: "Khajuraho Dance Festival", month: 2, day: 20, regionIds: ["madhya_pradesh"] },
  { id: "tansen_samaroh", label: "Tansen Samaroh", month: 12, day: 15, regionIds: ["madhya_pradesh"] },
  { id: "maharashtra_day", label: "Maharashtra Day", month: 5, day: 1, regionIds: ["maharashtra"] },
  { id: "shivaji_jayanti_maharashtra", label: "Chhatrapati Shivaji Maharaj Jayanti", month: 2, day: 19, regionIds: ["maharashtra"] },
  { id: "gudi_padwa", label: "Gudi Padwa", month: 3, day: 30, regionIds: ["maharashtra"] },
  { id: "ganesh_chaturthi_maharashtra", label: "Ganesh Chaturthi", month: 8, day: 27, regionIds: ["maharashtra"] },
  { id: "manipur_statehood_day", label: "Manipur Statehood Day", month: 1, day: 21, regionIds: ["manipur"] },
  { id: "yaoshang", label: "Yaoshang", month: 3, day: 14, regionIds: ["manipur"] },
  { id: "ningol_chakouba", label: "Ningol Chakouba", month: 11, day: 3, regionIds: ["manipur"] },
  { id: "sangai_festival", label: "Sangai Festival", month: 11, day: 21, regionIds: ["manipur"] },
  { id: "meghalaya_statehood_day", label: "Meghalaya Statehood Day", month: 1, day: 21, regionIds: ["meghalaya"] },
  { id: "shad_suk_mynsiem", label: "Shad Suk Mynsiem", month: 4, day: 14, regionIds: ["meghalaya"] },
  { id: "wangala", label: "Wangala Festival", month: 11, day: 14, regionIds: ["meghalaya"] },
  { id: "nongkrem_dance_festival", label: "Nongkrem Dance Festival", month: 11, day: 5, regionIds: ["meghalaya"] },
  { id: "mizoram_statehood_day", label: "Mizoram Statehood Day", month: 2, day: 20, regionIds: ["mizoram"] },
  { id: "chapchar_kut", label: "Chapchar Kut", month: 3, day: 7, regionIds: ["mizoram"] },
  { id: "mim_kut", label: "Mim Kut", month: 9, day: 1, regionIds: ["mizoram"] },
  { id: "pawl_kut", label: "Pawl Kut", month: 12, day: 11, regionIds: ["mizoram"] },
  { id: "nagaland_statehood_day", label: "Nagaland Statehood Day", month: 12, day: 1, regionIds: ["nagaland"] },
  { id: "hornbill_festival", label: "Hornbill Festival", month: 12, day: 1, regionIds: ["nagaland"] },
  { id: "moatsu", label: "Moatsu", month: 5, day: 1, regionIds: ["nagaland"] },
  { id: "sekrenyi", label: "Sekrenyi", month: 2, day: 25, regionIds: ["nagaland"] },
  { id: "odisha_day_utkala_dibasa", label: "Odisha Day / Utkala Dibasa", month: 4, day: 1, regionIds: ["odisha"] },
  { id: "raja_parba", label: "Raja Parba", month: 6, day: 14, regionIds: ["odisha"] },
  { id: "nuakhai_odisha", label: "Nuakhai", month: 9, day: 1, regionIds: ["odisha"] },
  { id: "rath_yatra_puri", label: "Puri Rath Yatra", month: 6, day: 27, regionIds: ["odisha"] },
  { id: "punjab_day", label: "Punjab Day", month: 11, day: 1, regionIds: ["punjab"] },
  { id: "lohri", label: "Lohri", month: 1, day: 13, regionIds: ["punjab"] },
  { id: "baisakhi_punjab", label: "Baisakhi", month: 4, day: 13, regionIds: ["punjab"] },
  { id: "hola_mohalla", label: "Hola Mohalla", month: 3, day: 15, regionIds: ["punjab"] },
  { id: "rajasthan_day", label: "Rajasthan Day", month: 3, day: 30, regionIds: ["rajasthan"] },
  { id: "gangaur", label: "Gangaur", month: 4, day: 2, regionIds: ["rajasthan"] },
  { id: "teej_rajasthan", label: "Teej", month: 8, day: 7, regionIds: ["rajasthan"] },
  { id: "pushkar_fair", label: "Pushkar Fair", month: 11, day: 9, regionIds: ["rajasthan"] },
  { id: "sikkim_state_day", label: "Sikkim State Day", month: 5, day: 16, regionIds: ["sikkim"] },
  { id: "saga_dawa", label: "Saga Dawa", month: 6, day: 11, regionIds: ["sikkim"] },
  { id: "pang_lhabsol", label: "Pang Lhabsol", month: 9, day: 8, regionIds: ["sikkim"] },
  { id: "losoong", label: "Losoong", month: 12, day: 19, regionIds: ["sikkim"] },
  { id: "tamil_new_year", label: "Tamil New Year / Puthandu", month: 4, day: 14, regionIds: ["tamil_nadu"] },
  { id: "pongal", label: "Pongal", month: 1, day: 15, regionIds: ["tamil_nadu"] },
  { id: "thaipusam", label: "Thaipusam", month: 2, day: 11, regionIds: ["tamil_nadu"] },
  { id: "tamil_nadu_day", label: "Tamil Nadu Day", month: 7, day: 18, regionIds: ["tamil_nadu"] },
  { id: "tripura_statehood_day", label: "Tripura Statehood Day", month: 1, day: 21, regionIds: ["tripura"] },
  { id: "garia_puja", label: "Garia Puja", month: 4, day: 21, regionIds: ["tripura"] },
  { id: "kharchi_puja", label: "Kharchi Puja", month: 7, day: 3, regionIds: ["tripura"] },
  { id: "ker_puja", label: "Ker Puja", month: 7, day: 17, regionIds: ["tripura"] },
  { id: "uttar_pradesh_day", label: "Uttar Pradesh Day", month: 1, day: 24, regionIds: ["uttar_pradesh"] },
  { id: "dev_deepawali_varanasi", label: "Dev Deepawali Varanasi", month: 11, day: 15, regionIds: ["uttar_pradesh"] },
  { id: "krishna_janmashtami_mathura", label: "Krishna Janmashtami Mathura", month: 8, day: 16, regionIds: ["uttar_pradesh"] },
  { id: "uttarakhand_state_foundation_day", label: "Uttarakhand State Foundation Day", month: 11, day: 9, regionIds: ["uttarakhand"] },
  { id: "harela", label: "Harela", month: 7, day: 16, regionIds: ["uttarakhand"] },
  { id: "phool_dei", label: "Phool Dei", month: 3, day: 14, regionIds: ["uttarakhand"] },
  { id: "poila_boishakh", label: "Poila Boishakh", month: 4, day: 15, regionIds: ["west_bengal"] },
  { id: "durga_puja_west_bengal", label: "Durga Puja", month: 10, day: 9, regionIds: ["west_bengal"] },
  { id: "kali_puja_west_bengal", label: "Kali Puja", month: 10, day: 31, regionIds: ["west_bengal"] },
  { id: "west_bengal_day", label: "West Bengal Day", month: 4, day: 15, regionIds: ["west_bengal"] },
  { id: "delhi_formation_day", label: "Delhi Formation Day", month: 2, day: 1, regionIds: ["delhi"] },
  { id: "jammu_kashmir_union_territory_day", label: "Jammu & Kashmir Union Territory Day", month: 10, day: 31, regionIds: ["jammu_kashmir"] },
  { id: "tulip_festival_kashmir", label: "Kashmir Tulip Festival", month: 4, day: 1, regionIds: ["jammu_kashmir"] },
  { id: "ladakh_union_territory_day", label: "Ladakh Union Territory Day", month: 10, day: 31, regionIds: ["ladakh"] },
  { id: "hemis_festival", label: "Hemis Festival", month: 6, day: 16, regionIds: ["ladakh"] },
  { id: "puducherry_liberation_day", label: "Puducherry Liberation Day", month: 11, day: 1, regionIds: ["puducherry"] },
  { id: "de_jure_transfer_day", label: "De Jure Transfer Day", month: 8, day: 16, regionIds: ["puducherry"] },
  { id: "chandigarh_capital_day", label: "Chandigarh Capital Day", month: 11, day: 1, regionIds: ["chandigarh"] },
  { id: "island_tourism_festival", label: "Island Tourism Festival", month: 1, day: 5, regionIds: ["andaman_nicobar"] },
  { id: "andaman_nicobar_formation_day", label: "Andaman & Nicobar Formation Day", month: 11, day: 1, regionIds: ["andaman_nicobar"] },
  { id: "lakshadweep_formation_day", label: "Lakshadweep Formation Day", month: 11, day: 1, regionIds: ["lakshadweep"] },
  { id: "dadra_nagar_haveli_daman_diu_merger_day", label: "Dadra & Nagar Haveli and Daman & Diu Merger Day", month: 1, day: 26, regionIds: ["dadra_nagar_haveli_daman_diu"] },
  { id: "si_donyi", label: "Si-Donyi", month: 1, day: 6, regionIds: ["arunachal_pradesh"] },
  { id: "dree_festival", label: "Dree Festival", month: 7, day: 5, regionIds: ["arunachal_pradesh"] },
  { id: "torgya_festival", label: "Torgya Festival", month: 1, day: 28, regionIds: ["arunachal_pradesh"] },
  { id: "reh_festival", label: "Reh Festival", month: 2, day: 1, regionIds: ["arunachal_pradesh"] },
  { id: "ali_ai_ligang", label: "Ali-Ai-Ligang", month: 2, day: 15, regionIds: ["assam"] },
  { id: "baishagu", label: "Baishagu", month: 4, day: 14, regionIds: ["assam"] },
  { id: "ambubachi_mela", label: "Ambubachi Mela", month: 6, day: 22, regionIds: ["assam"] },
  { id: "me_dam_me_phi", label: "Me-Dam-Me-Phi", month: 1, day: 31, regionIds: ["assam"] },
  { id: "sama_chakeva", label: "Sama Chakeva", month: 11, day: 18, regionIds: ["bihar"] },
  { id: "pitrapaksha_mela_gaya", label: "Pitrapaksha Mela Gaya", month: 9, day: 15, regionIds: ["bihar"] },
  { id: "rajgir_mahotsav", label: "Rajgir Mahotsav", month: 11, day: 25, regionIds: ["bihar"] },
  { id: "bastar_dussehra", label: "Bastar Dussehra", month: 10, day: 1, regionIds: ["chhattisgarh"] },
  { id: "madai_festival", label: "Madai Festival", month: 12, day: 1, regionIds: ["chhattisgarh"] },
  { id: "goncha_festival", label: "Goncha Festival", month: 7, day: 1, regionIds: ["chhattisgarh"] },
  { id: "goa_carnival", label: "Goa Carnival", month: 2, day: 10, regionIds: ["goa"] },
  { id: "bonderam_festival", label: "Bonderam Festival", month: 8, day: 24, regionIds: ["goa"] },
  { id: "three_kings_feast", label: "Three Kings Feast", month: 1, day: 6, regionIds: ["goa"] },
  { id: "modhera_dance_festival", label: "Modhera Dance Festival", month: 1, day: 19, regionIds: ["gujarat"] },
  { id: "tarnetar_fair", label: "Tarnetar Fair", month: 9, day: 5, regionIds: ["gujarat"] },
  { id: "dwarka_janmashtami", label: "Dwarka Janmashtami", month: 8, day: 16, regionIds: ["gujarat"] },
  { id: "phag_festival", label: "Phag Festival", month: 3, day: 1, regionIds: ["haryana"] },
  { id: "gugga_naumi", label: "Gugga Naumi", month: 8, day: 20, regionIds: ["haryana"] },
  { id: "kartik_cultural_festival", label: "Kartik Cultural Festival", month: 11, day: 15, regionIds: ["haryana"] },
  { id: "mandi_shivaratri_fair", label: "Mandi Shivaratri Fair", month: 3, day: 8, regionIds: ["himachal_pradesh"] },
  { id: "halda_festival", label: "Halda Festival", month: 1, day: 15, regionIds: ["himachal_pradesh"] },
  { id: "lavi_fair", label: "Lavi Fair", month: 11, day: 11, regionIds: ["himachal_pradesh"] },
  { id: "tusu_parab", label: "Tusu Parab", month: 1, day: 15, regionIds: ["jharkhand"] },
  { id: "mage_parab", label: "Mage Parab", month: 2, day: 1, regionIds: ["jharkhand"] },
  { id: "rohini_festival", label: "Rohini Festival", month: 6, day: 1, regionIds: ["jharkhand"] },
  { id: "ugadi_karnataka", label: "Ugadi", month: 3, day: 30, regionIds: ["karnataka"] },
  { id: "karaga_festival", label: "Karaga Festival", month: 4, day: 12, regionIds: ["karnataka"] },
  { id: "hampi_utsav", label: "Hampi Utsav", month: 1, day: 10, regionIds: ["karnataka"] },
  { id: "onam", label: "Onam", month: 9, day: 5, regionIds: ["kerala"] },
  { id: "nehru_trophy_boat_race", label: "Nehru Trophy Boat Race", month: 8, day: 10, regionIds: ["kerala"] },
  { id: "makaravilakku", label: "Makaravilakku", month: 1, day: 14, regionIds: ["kerala"] },
  { id: "lokrang_festival", label: "Lokrang Festival", month: 1, day: 26, regionIds: ["madhya_pradesh"] },
  { id: "bhagoria_festival", label: "Bhagoria Festival", month: 3, day: 1, regionIds: ["madhya_pradesh"] },
  { id: "malwa_utsav", label: "Malwa Utsav", month: 5, day: 2, regionIds: ["madhya_pradesh"] },
  { id: "dahi_handi", label: "Dahi Handi", month: 8, day: 16, regionIds: ["maharashtra"] },
  { id: "ashadhi_wari", label: "Ashadhi Wari", month: 7, day: 6, regionIds: ["maharashtra"] },
  { id: "ambedkar_jayanti_maharashtra", label: "Dr. Ambedkar Jayanti", month: 4, day: 14, regionIds: ["maharashtra"] },
  { id: "cheiraoba", label: "Cheiraoba", month: 4, day: 14, regionIds: ["manipur"] },
  { id: "kut_festival", label: "Kut Festival", month: 11, day: 1, regionIds: ["manipur"] },
  { id: "lui_ngai_ni", label: "Lui-Ngai-Ni", month: 2, day: 15, regionIds: ["manipur"] },
  { id: "behdienkhlam", label: "Behdienkhlam", month: 7, day: 10, regionIds: ["meghalaya"] },
  { id: "meghalaya_autumn_festival", label: "Meghalaya Autumn Festival", month: 10, day: 25, regionIds: ["meghalaya"] },
  { id: "strawberry_festival_meghalaya", label: "Strawberry Festival", month: 2, day: 14, regionIds: ["meghalaya"] },
  { id: "thalfavang_kut", label: "Thalfavang Kut", month: 11, day: 15, regionIds: ["mizoram"] },
  { id: "anthurium_festival", label: "Anthurium Festival", month: 9, day: 20, regionIds: ["mizoram"] },
  { id: "aoling_festival", label: "Aoling Festival", month: 4, day: 1, regionIds: ["nagaland"] },
  { id: "tokhu_emong", label: "Tokhu Emong", month: 11, day: 7, regionIds: ["nagaland"] },
  { id: "tuluni_festival", label: "Tuluni Festival", month: 7, day: 8, regionIds: ["nagaland"] },
  { id: "konark_dance_festival", label: "Konark Dance Festival", month: 12, day: 1, regionIds: ["odisha"] },
  { id: "bali_jatra", label: "Bali Jatra", month: 11, day: 15, regionIds: ["odisha"] },
  { id: "chhau_festival", label: "Chhau Festival", month: 4, day: 11, regionIds: ["odisha"] },
  { id: "maghi_mela", label: "Maghi Mela", month: 1, day: 14, regionIds: ["punjab"] },
  { id: "basant_panchami_punjab", label: "Basant Panchami", month: 2, day: 2, regionIds: ["punjab"] },
  { id: "shaheedi_jor_mela", label: "Shaheedi Jor Mela", month: 12, day: 25, regionIds: ["punjab"] },
  { id: "desert_festival_jaisalmer", label: "Jaisalmer Desert Festival", month: 2, day: 22, regionIds: ["rajasthan"] },
  { id: "marwar_festival", label: "Marwar Festival", month: 10, day: 12, regionIds: ["rajasthan"] },
  { id: "mewar_festival", label: "Mewar Festival", month: 4, day: 1, regionIds: ["rajasthan"] },
  { id: "bhumchu", label: "Bhumchu", month: 3, day: 10, regionIds: ["sikkim"] },
  { id: "tendong_lho_rum_faat", label: "Tendong Lho Rum Faat", month: 8, day: 8, regionIds: ["sikkim"] },
  { id: "maghe_sankranti_sikkim", label: "Maghe Sankranti", month: 1, day: 15, regionIds: ["sikkim"] },
  { id: "karthigai_deepam", label: "Karthigai Deepam", month: 12, day: 13, regionIds: ["tamil_nadu"] },
  { id: "chithirai_thiruvizha", label: "Chithirai Thiruvizha", month: 4, day: 15, regionIds: ["tamil_nadu"] },
  { id: "aadi_perukku", label: "Aadi Perukku", month: 8, day: 3, regionIds: ["tamil_nadu"] },
  { id: "diwali_tripureswari", label: "Diwali at Tripureswari Temple", month: 10, day: 31, regionIds: ["tripura"] },
  { id: "neermahal_festival", label: "Neermahal Festival", month: 8, day: 1, regionIds: ["tripura"] },
  { id: "orange_tourism_festival", label: "Orange & Tourism Festival", month: 11, day: 20, regionIds: ["tripura"] },
  { id: "lathmar_holi", label: "Lathmar Holi", month: 3, day: 7, regionIds: ["uttar_pradesh"] },
  { id: "taj_mahotsav", label: "Taj Mahotsav", month: 2, day: 18, regionIds: ["uttar_pradesh"] },
  { id: "nauchandi_mela", label: "Nauchandi Mela", month: 3, day: 15, regionIds: ["uttar_pradesh"] },
  { id: "ganga_dussehra_uttarakhand", label: "Ganga Dussehra", month: 6, day: 16, regionIds: ["uttarakhand"] },
  { id: "bikhauti_mela", label: "Bikhauti Mela", month: 4, day: 14, regionIds: ["uttarakhand"] },
  { id: "nanda_devi_fair", label: "Nanda Devi Fair", month: 9, day: 1, regionIds: ["uttarakhand"] },
  { id: "saraswati_puja_west_bengal", label: "Saraswati Puja", month: 2, day: 2, regionIds: ["west_bengal"] },
  { id: "rabindra_jayanti", label: "Rabindra Jayanti", month: 5, day: 7, regionIds: ["west_bengal"] },
  { id: "jagaddhatri_puja", label: "Jagaddhatri Puja", month: 11, day: 8, regionIds: ["west_bengal"] },
  { id: "phool_walon_ki_sair", label: "Phool Walon Ki Sair", month: 9, day: 15, regionIds: ["delhi"] },
  { id: "qutub_festival", label: "Qutub Festival", month: 11, day: 15, regionIds: ["delhi"] },
  { id: "india_international_trade_fair", label: "India International Trade Fair", month: 11, day: 14, regionIds: ["delhi"] },
  { id: "kheer_bhawani_mela", label: "Kheer Bhawani Mela", month: 6, day: 10, regionIds: ["jammu_kashmir"] },
  { id: "bahu_mela", label: "Bahu Mela", month: 4, day: 1, regionIds: ["jammu_kashmir"] },
  { id: "shikara_festival", label: "Shikara Festival", month: 7, day: 1, regionIds: ["jammu_kashmir"] },
  { id: "losar_ladakh", label: "Losar Ladakh", month: 12, day: 30, regionIds: ["ladakh"] },
  { id: "sindhu_darshan", label: "Sindhu Darshan Festival", month: 6, day: 12, regionIds: ["ladakh"] },
  { id: "ladakh_festival", label: "Ladakh Festival", month: 9, day: 1, regionIds: ["ladakh"] },
  { id: "bastille_day_puducherry", label: "Bastille Day Puducherry", month: 7, day: 14, regionIds: ["puducherry"] },
  { id: "fete_de_puducherry", label: "Fete de Puducherry", month: 8, day: 15, regionIds: ["puducherry"] },
  { id: "masimagam_puducherry", label: "Masimagam", month: 3, day: 6, regionIds: ["puducherry"] },
  { id: "rose_festival_chandigarh", label: "Rose Festival", month: 2, day: 23, regionIds: ["chandigarh"] },
  { id: "mango_mela_chandigarh", label: "Mango Mela", month: 7, day: 6, regionIds: ["chandigarh"] },
  { id: "chrysanthemum_show_chandigarh", label: "Chrysanthemum Show", month: 12, day: 13, regionIds: ["chandigarh"] },
  { id: "andaman_beach_festival", label: "Andaman Beach Festival", month: 4, day: 15, regionIds: ["andaman_nicobar"] },
  { id: "subhash_chandra_bose_island_day", label: "Subhash Chandra Bose Island Day", month: 12, day: 30, regionIds: ["andaman_nicobar"] },
  { id: "minicoy_fest", label: "Minicoy Fest", month: 12, day: 1, regionIds: ["lakshadweep"] },
  { id: "lakshadweep_lagoon_festival", label: "Lakshadweep Lagoon Festival", month: 1, day: 10, regionIds: ["lakshadweep"] },
  { id: "tarpa_festival", label: "Tarpa Festival", month: 12, day: 25, regionIds: ["dadra_nagar_haveli_daman_diu"] },
  { id: "nariyal_poornima_daman_diu", label: "Nariyal Poornima", month: 8, day: 19, regionIds: ["dadra_nagar_haveli_daman_diu"] },
  { id: "daman_ganga_festival", label: "Daman Ganga Festival", month: 12, day: 19, regionIds: ["dadra_nagar_haveli_daman_diu"] },
  { id: "mannam_jayanthi", label: "Mannam Jayanthi", month: 1, day: 2, regionIds: ["kerala"] },
  { id: "sree_narayana_guru_samadhi", label: "Sree Narayana Guru Samadhi", month: 9, day: 21, regionIds: ["kerala"] },
  { id: "ayyankali_jayanthi", label: "Ayyankali Jayanthi", month: 8, day: 28, regionIds: ["kerala"] },
  { id: "karkidaka_vavu", label: "Karkidaka Vavu", month: 8, day: 12, regionIds: ["kerala"] },
  { id: "theyyam_season", label: "Theyyam Season", month: 12, day: 1, regionIds: ["kerala"] },
  { id: "aranmula_boat_race", label: "Aranmula Boat Race", month: 9, day: 10, regionIds: ["kerala"] },
  { id: "periyar_jayanthi", label: "Periyar Jayanthi", month: 9, day: 17, regionIds: ["tamil_nadu"] },
  { id: "kamarajar_jayanthi", label: "Kamarajar Jayanthi / Educational Development Day", month: 7, day: 15, regionIds: ["tamil_nadu"] },
  { id: "anna_jayanthi", label: "C.N. Annadurai Jayanthi", month: 9, day: 15, regionIds: ["tamil_nadu"] },
  { id: "m_g_ramachandran_jayanthi", label: "M.G. Ramachandran Jayanthi", month: 1, day: 17, regionIds: ["tamil_nadu"] },
  { id: "jayalalithaa_jayanthi", label: "J. Jayalalithaa Jayanthi", month: 2, day: 24, regionIds: ["tamil_nadu"] },
  { id: "jayalalithaa_vardhanthi", label: "J. Jayalalithaa Vardhanthi", month: 12, day: 5, regionIds: ["tamil_nadu"] },
  { id: "kempegowda_jayanthi", label: "Kempegowda Jayanthi", month: 6, day: 27, regionIds: ["karnataka"] },
  { id: "kuvempu_jayanthi", label: "Kuvempu Jayanthi", month: 12, day: 29, regionIds: ["karnataka"] },
  { id: "kanakadasa_vardhanthi", label: "Kanakadasa Vardhanthi", month: 12, day: 15, regionIds: ["karnataka"] },
  { id: "kittur_rani_chennamma_jayanthi", label: "Kittur Rani Chennamma Jayanthi", month: 10, day: 23, regionIds: ["karnataka"] },
  { id: "savitribai_phule_jayanthi", label: "Savitribai Phule Jayanthi", month: 1, day: 3, regionIds: ["maharashtra"] },
  { id: "jyotiba_phule_jayanthi", label: "Jyotiba Phule Jayanthi", month: 4, day: 11, regionIds: ["maharashtra"] },
  { id: "shahu_maharaj_jayanthi", label: "Chhatrapati Shahu Maharaj Jayanthi", month: 6, day: 26, regionIds: ["maharashtra"] },
  { id: "bal_gangadhar_tilak_vardhanthi", label: "Bal Gangadhar Tilak Vardhanthi", month: 8, day: 1, regionIds: ["maharashtra"] },
  { id: "zaverchand_meghani_jayanthi", label: "Zaverchand Meghani Jayanthi", month: 8, day: 28, regionIds: ["gujarat"] },
  { id: "narmad_jayanthi", label: "Narmad Jayanthi", month: 8, day: 24, regionIds: ["gujarat"] },
  { id: "sardar_patel_vardhanthi_gujarat", label: "Sardar Patel Vardhanthi", month: 12, day: 15, regionIds: ["gujarat"] },
  { id: "ishwar_chandra_vidyasagar_jayanthi", label: "Ishwar Chandra Vidyasagar Jayanthi", month: 9, day: 26, regionIds: ["west_bengal"] },
  { id: "ishwar_chandra_vidyasagar_vardhanthi", label: "Ishwar Chandra Vidyasagar Vardhanthi", month: 7, day: 29, regionIds: ["west_bengal"] },
  { id: "matangini_hazra_vardhanthi", label: "Matangini Hazra Vardhanthi", month: 9, day: 29, regionIds: ["west_bengal"] },
  { id: "biju_patnaik_jayanthi", label: "Biju Patnaik Jayanthi / Panchayati Raj Diwas", month: 3, day: 5, regionIds: ["odisha"] },
  { id: "madhusudan_das_jayanthi", label: "Madhusudan Das Jayanthi", month: 4, day: 28, regionIds: ["odisha"] },
  { id: "gopabandhu_das_jayanthi", label: "Gopabandhu Das Jayanthi", month: 10, day: 9, regionIds: ["odisha"] },
  { id: "karpoori_thakur_jayanthi", label: "Karpoori Thakur Jayanthi", month: 1, day: 24, regionIds: ["bihar"] },
  { id: "dr_rajendra_prasad_jayanthi", label: "Dr. Rajendra Prasad Jayanthi", month: 12, day: 3, regionIds: ["bihar"] },
  { id: "jayaprakash_narayan_jayanthi", label: "Jayaprakash Narayan Jayanthi", month: 10, day: 11, regionIds: ["bihar"] },
  { id: "veer_kunwar_singh_jayanthi", label: "Veer Kunwar Singh Jayanthi", month: 4, day: 23, regionIds: ["bihar"] },
  { id: "ram_manohar_lohia_jayanthi", label: "Ram Manohar Lohia Jayanthi", month: 3, day: 23, regionIds: ["uttar_pradesh"] },
  { id: "deendayal_upadhyaya_jayanthi", label: "Deendayal Upadhyaya Jayanthi", month: 9, day: 25, regionIds: ["uttar_pradesh"] },
  { id: "atal_bihari_vajpayee_jayanthi", label: "Atal Bihari Vajpayee Jayanthi", month: 12, day: 25, regionIds: ["uttar_pradesh"] },
  { id: "atal_bihari_vajpayee_vardhanthi", label: "Atal Bihari Vajpayee Vardhanthi", month: 8, day: 16, regionIds: ["uttar_pradesh"] },
  { id: "maharana_pratap_jayanthi", label: "Maharana Pratap Jayanthi", month: 5, day: 9, regionIds: ["rajasthan"] },
  { id: "panna_dhai_jayanthi", label: "Panna Dhai Jayanthi", month: 3, day: 8, regionIds: ["rajasthan"] },
  { id: "gogaji_jayanthi", label: "Gogaji Jayanthi", month: 8, day: 20, regionIds: ["rajasthan"] },
  { id: "shaheed_udham_singh_vardhanthi", label: "Shaheed Udham Singh Vardhanthi", month: 7, day: 31, regionIds: ["punjab"] },
  { id: "maharaja_ranjit_singh_vardhanthi", label: "Maharaja Ranjit Singh Vardhanthi", month: 6, day: 27, regionIds: ["punjab"] },
  { id: "bhagat_singh_vardhanthi_punjab", label: "Bhagat Singh Vardhanthi / Shaheed Diwas", month: 3, day: 23, regionIds: ["punjab"] },
  { id: "deenbandhu_chhotu_ram_jayanthi", label: "Deenbandhu Chhotu Ram Jayanthi", month: 11, day: 24, regionIds: ["haryana"] },
  { id: "kalpana_chawla_jayanthi", label: "Kalpana Chawla Jayanthi", month: 3, day: 17, regionIds: ["haryana"] },
  { id: "sidhu_kanhu_hul_diwas", label: "Sidhu Kanhu Hul Diwas", month: 6, day: 30, regionIds: ["jharkhand"] },
  { id: "tilka_manjhi_jayanthi", label: "Tilka Manjhi Jayanthi", month: 2, day: 11, regionIds: ["jharkhand"] },
  { id: "jaipal_singh_munda_jayanthi", label: "Jaipal Singh Munda Jayanthi", month: 1, day: 3, regionIds: ["jharkhand"] },
  { id: "tantya_bhil_vardhanthi", label: "Tantya Bhil Vardhanthi", month: 12, day: 4, regionIds: ["madhya_pradesh"] },
  { id: "rani_durgavati_jayanthi", label: "Rani Durgavati Jayanthi", month: 10, day: 5, regionIds: ["madhya_pradesh"] },
  { id: "rani_durgavati_vardhanthi", label: "Rani Durgavati Vardhanthi", month: 6, day: 24, regionIds: ["madhya_pradesh"] },
  { id: "guru_ghasidas_jayanthi", label: "Guru Ghasidas Jayanthi", month: 12, day: 18, regionIds: ["chhattisgarh"] },
  { id: "veer_narayan_singh_vardhanthi", label: "Veer Narayan Singh Vardhanthi", month: 12, day: 10, regionIds: ["chhattisgarh"] },
  { id: "gopinath_bordoloi_vardhanthi", label: "Gopinath Bordoloi Vardhanthi", month: 8, day: 5, regionIds: ["assam"] },
  { id: "jyoti_prasad_agarwala_vardhanthi", label: "Jyoti Prasad Agarwala Vardhanthi / Silpi Divas", month: 1, day: 17, regionIds: ["assam"] },
  { id: "bishnu_prasad_rabha_vardhanthi", label: "Bishnu Prasad Rabha Vardhanthi / Rabha Divas", month: 6, day: 20, regionIds: ["assam"] },
  { id: "bir_tikendrajit_vardhanthi", label: "Bir Tikendrajit Vardhanthi / Patriots Day", month: 8, day: 13, regionIds: ["manipur"] },
  { id: "nupi_lan_day", label: "Nupi Lan Day", month: 12, day: 12, regionIds: ["manipur"] },
  { id: "u_tirot_singh_day", label: "U Tirot Singh Day", month: 7, day: 17, regionIds: ["meghalaya"] },
  { id: "u_kiang_nangbah_day", label: "U Kiang Nangbah Day", month: 12, day: 30, regionIds: ["meghalaya"] },
  { id: "remna_ni", label: "Remna Ni / Peace Accord Day", month: 6, day: 30, regionIds: ["mizoram"] },
  { id: "zoram_ni", label: "Zoram Ni", month: 6, day: 21, regionIds: ["mizoram"] },
  { id: "naga_national_day", label: "Naga National Day", month: 8, day: 14, regionIds: ["nagaland"] },
  { id: "jorethang_maghey_mela", label: "Jorethang Maghey Mela", month: 1, day: 15, regionIds: ["sikkim"] },
  { id: "red_panda_winter_festival", label: "Red Panda Winter Festival", month: 12, day: 15, regionIds: ["sikkim"] },
  { id: "chabimura_festival", label: "Chabimura Festival", month: 1, day: 15, regionIds: ["tripura"] },
  { id: "tirthamukh_festival", label: "Tirthamukh Festival", month: 1, day: 14, regionIds: ["tripura"] },
  { id: "ashokastami_mela", label: "Ashokastami Mela", month: 4, day: 8, regionIds: ["tripura"] },
  { id: "veer_savarkar_jayanthi_andaman", label: "Veer Savarkar Jayanthi", month: 5, day: 28, regionIds: ["andaman_nicobar"] },
  { id: "veer_savarkar_vardhanthi_andaman", label: "Veer Savarkar Vardhanthi", month: 2, day: 26, regionIds: ["andaman_nicobar"] },
  { id: "daying_ering_jayanthi", label: "Dr. Daying Ering Jayanthi", month: 12, day: 11, regionIds: ["arunachal_pradesh"] },
  { id: "daying_ering_vardhanthi", label: "Dr. Daying Ering Vardhanthi", month: 6, day: 21, regionIds: ["arunachal_pradesh"] },
  { id: "gopinath_bordoloi_jayanthi", label: "Gopinath Bordoloi Jayanthi", month: 6, day: 6, regionIds: ["assam"] },
  { id: "karpoori_thakur_vardhanthi", label: "Karpoori Thakur Vardhanthi", month: 2, day: 17, regionIds: ["bihar"] },
  { id: "le_corbusier_jayanthi_chandigarh", label: "Le Corbusier Jayanthi", month: 10, day: 6, regionIds: ["chandigarh"] },
  { id: "le_corbusier_vardhanthi_chandigarh", label: "Le Corbusier Vardhanthi", month: 8, day: 27, regionIds: ["chandigarh"] },
  { id: "govind_guru_jayanthi_dnhdd", label: "Govind Guru Jayanthi", month: 12, day: 20, regionIds: ["dadra_nagar_haveli_daman_diu"] },
  { id: "govind_guru_vardhanthi_dnhdd", label: "Govind Guru Vardhanthi", month: 10, day: 30, regionIds: ["dadra_nagar_haveli_daman_diu"] },
  { id: "mirza_ghalib_jayanthi_delhi", label: "Mirza Ghalib Jayanthi", month: 12, day: 27, regionIds: ["delhi"] },
  { id: "mirza_ghalib_vardhanthi_delhi", label: "Mirza Ghalib Vardhanthi", month: 2, day: 15, regionIds: ["delhi"] },
  { id: "t_b_cunha_jayanthi", label: "T.B. Cunha Jayanthi", month: 4, day: 2, regionIds: ["goa"] },
  { id: "t_b_cunha_vardhanthi", label: "T.B. Cunha Vardhanthi", month: 9, day: 26, regionIds: ["goa"] },
  { id: "deenbandhu_chhotu_ram_vardhanthi", label: "Deenbandhu Chhotu Ram Vardhanthi", month: 1, day: 9, regionIds: ["haryana"] },
  { id: "y_s_parmar_jayanthi", label: "Dr. Y.S. Parmar Jayanthi", month: 8, day: 4, regionIds: ["himachal_pradesh"] },
  { id: "y_s_parmar_vardhanthi", label: "Dr. Y.S. Parmar Vardhanthi", month: 5, day: 2, regionIds: ["himachal_pradesh"] },
  { id: "sheikh_abdullah_jayanthi", label: "Sheikh Abdullah Jayanthi", month: 12, day: 5, regionIds: ["jammu_kashmir"] },
  { id: "sheikh_abdullah_vardhanthi", label: "Sheikh Abdullah Vardhanthi", month: 9, day: 8, regionIds: ["jammu_kashmir"] },
  { id: "tilka_manjhi_vardhanthi", label: "Tilka Manjhi Vardhanthi", month: 1, day: 13, regionIds: ["jharkhand"] },
  { id: "kushok_bakula_jayanthi", label: "Kushok Bakula Rinpoche Jayanthi", month: 5, day: 19, regionIds: ["ladakh"] },
  { id: "kushok_bakula_vardhanthi", label: "Kushok Bakula Rinpoche Vardhanthi", month: 11, day: 4, regionIds: ["ladakh"] },
  { id: "sardar_patel_jayanthi_lakshadweep", label: "Sardar Patel Jayanthi", month: 10, day: 31, regionIds: ["lakshadweep"] },
  { id: "sardar_patel_vardhanthi_lakshadweep", label: "Sardar Patel Vardhanthi", month: 12, day: 15, regionIds: ["lakshadweep"] },
  { id: "rani_gaidinliu_jayanthi_manipur", label: "Rani Gaidinliu Jayanthi", month: 1, day: 26, regionIds: ["manipur"] },
  { id: "williamson_sangma_jayanthi", label: "Williamson A. Sangma Jayanthi", month: 10, day: 18, regionIds: ["meghalaya"] },
  { id: "laldenga_jayanthi", label: "Laldenga Jayanthi", month: 6, day: 11, regionIds: ["mizoram"] },
  { id: "laldenga_vardhanthi", label: "Laldenga Vardhanthi", month: 7, day: 7, regionIds: ["mizoram"] },
  { id: "a_z_phizo_jayanthi", label: "A.Z. Phizo Jayanthi", month: 5, day: 16, regionIds: ["nagaland"] },
  { id: "a_z_phizo_vardhanthi", label: "A.Z. Phizo Vardhanthi", month: 4, day: 30, regionIds: ["nagaland"] },
  { id: "biju_patnaik_vardhanthi", label: "Biju Patnaik Vardhanthi", month: 4, day: 17, regionIds: ["odisha"] },
  { id: "bharathidasan_jayanthi_puducherry", label: "Bharathidasan Jayanthi", month: 4, day: 29, regionIds: ["puducherry"] },
  { id: "bharathidasan_vardhanthi_puducherry", label: "Bharathidasan Vardhanthi", month: 4, day: 21, regionIds: ["puducherry"] },
  { id: "shaheed_udham_singh_jayanthi", label: "Shaheed Udham Singh Jayanthi", month: 12, day: 26, regionIds: ["punjab"] },
  { id: "maharana_pratap_vardhanthi", label: "Maharana Pratap Vardhanthi", month: 1, day: 19, regionIds: ["rajasthan"] },
  { id: "tashi_namgyal_jayanthi", label: "Tashi Namgyal Jayanthi", month: 10, day: 26, regionIds: ["sikkim"] },
  { id: "tashi_namgyal_vardhanthi", label: "Tashi Namgyal Vardhanthi", month: 12, day: 2, regionIds: ["sikkim"] },
  { id: "bir_bikram_jayanthi", label: "Maharaja Bir Bikram Jayanthi", month: 8, day: 19, regionIds: ["tripura"] },
  { id: "bir_bikram_vardhanthi", label: "Maharaja Bir Bikram Vardhanthi", month: 5, day: 17, regionIds: ["tripura"] },
  { id: "govind_ballabh_pant_jayanthi_uttarakhand", label: "Govind Ballabh Pant Jayanthi", month: 9, day: 10, regionIds: ["uttarakhand"] },
  { id: "govind_ballabh_pant_vardhanthi_uttarakhand", label: "Govind Ballabh Pant Vardhanthi", month: 3, day: 7, regionIds: ["uttarakhand"] },
];
